########################################
#   DO NOT EDIT THIS FILE!             #
#   Your changes will be overwritten   #
########################################

#######################
# Ubuntu Repos Groovy #
#######################

deb http://archive.ubuntu.com/ubuntu groovy main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu groovy-security main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu groovy-updates main restricted universe multiverse