#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Exit on errors.

set -e


# -- Wrap APT commands in functions.

add_nitrux_key_depot () { curl -L https://packagecloud.io/nitrux/depot/gpgkey | apt-key add -; }
add_nitrux_key_unison () { curl -L https://packagecloud.io/nitrux/unison/gpgkey | apt-key add -; }
add_nitrux_key_testing () { curl -L https://packagecloud.io/nitrux/testing/gpgkey | apt-key add -; }
add_nitrux_key_area51 () { curl -L https://packagecloud.io/nitrux/area51/gpgkey | apt-key add -; }
add_nitrux_key_skidrow () { curl -L https://packagecloud.io/nitrux/skidrow/gpgkey | apt-key add -; }
add_repo_keys () { apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "$@"; }
appstream_refresh_force () { appstreamcli refresh --force; }
autoremove () { apt -yy autoremove "$@"; }
clean_all () { apt clean && apt autoclean; }
dist_upgrade () { apt -yy dist-upgrade "$@"; }
download () { apt download "$@"; }
dpkg_conf () { dpkg --configure -a; }
dpkg_force_install () { dpkg --force-all -i "$@"; }
dpkg_force_remove () { /usr/bin/dpkg --remove --no-triggers --force-remove-essential --force-bad-path "$@"; }
dpkg_install () { dpkg -i "$@"; }
fix_install () { apt -yy --fix-broken install "$@"; }
fix_install_no_recommends () { apt -yy --fix-broken install --no-install-recommends "$@"; }
hold () { apt-mark hold "$@"; }
install () { apt -yy install --no-install-recommends "$@"; }
install_full () { apt -yy install "$@"; }
install_downgrades () { apt -yy install --no-install-recommends --allow-downgrades "$@"; }
install_downgrades_hold () { apt -yy install --no-install-recommends --allow-downgrades --allow-change-held-packages "$@"; }
install_force_overwrite () { apt -yy install --no-install-recommends -o Dpkg::Options::="--force-overwrite" "$@"; }
install_hold () { apt -yy install --no-install-recommends "$@" && apt-mark hold "$@"; }
list_installed_apt () { apt list --installed; }
list_installed_dpkg () { dpkg --list '*'; }
list_installed_text_start () { dpkg-query -l | less > installed_pkgs_start.txt; }
list_installed_text_end () { dpkg-query -l | less > installed_pkgs_end.txt; }
list_number_pkgs () { dpkg-query -f '${binary:Package}\n' -W | wc -l; }
list_pkgs_size () { dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | head -25 | awk '{print $1/1024, $2}'; }
list_upgrade () { apt list --upgradable; }
only_upgrade () { apt -yy install --no-install-recommends --only-upgrade "$@"; }
only_upgrade_force_overwrite () { apt -yy install --no-install-recommends --only-upgrade -o Dpkg::Options::="--force-overwrite" "$@"; }
pkg_policy () { apt-cache policy "$@"; }
pkg_search () { apt-cache search "$@"; }
purge () { apt -yy purge --remove "$@"; }
purge_autoremove () { apt -yy purge --remove "$@" && apt -yy autoremove "$@"; }
remove () { apt -yy remove "$@"; }
remove_repo_keys () { apt-key del "$@"; }
unhold () { apt-mark unhold "$@"; }
update () { apt update; }
update_quiet () { apt -qq update; }
upgrade () { apt -yy upgrade "$@"; }
upgrade_downgrades () { apt -yy upgrade --allow-downgrades "$@"; }
