#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>



# -- Exit on errors.

set -e


# -- Add our repository keys.

add_nitrux_key () {
    KEYRING_DIR="/etc/apt/keyrings"
    mkdir -p "$KEYRING_DIR"

    local repo="$1"
    local url="https://packagecloud.io/nitrux/${repo}/gpgkey"
    local dest="${KEYRING_DIR}/nitrux-${repo}.gpg"

    curl -fsSL "$url" | gpg --dearmor -o "$dest"

    chmod 644 "$dest"
}


# -- Retrieve third-party repository keys using GPG.

add_third_party_repo_keys () {
    for key in "$@"; do
        gpg --batch --keyserver hkps://keyserver.ubuntu.com --recv-keys "$key"
        gpg --batch --yes --output "${KEYRING_DIR}/${key}.gpg" --export "$key"
    done
}


# -- Wrap APT commands in functions.

autoremove () { apt -yy autoremove "$@"; }
clean_all () { apt clean && apt autoclean; }
dist_upgrade () { apt -yy dist-upgrade "$@"; }
download () { apt download "$@"; }
fix_install () { apt -yy --fix-broken install "$@"; }
fix_install_no_recommends () { apt -yy --fix-broken install --no-install-recommends "$@"; }
hold () { apt-mark hold "$@"; }
install () { apt -yy install --no-install-recommends "$@"; }
install_full () { apt -yy install "$@"; }
install_downgrades () { apt -yy install --no-install-recommends --allow-downgrades "$@"; }
install_downgrades_hold () { apt -yy install --no-install-recommends --allow-downgrades --allow-change-held-packages "$@"; }
install_force_overwrite () { apt -yy install --no-install-recommends -o Dpkg::Options::="--force-overwrite" "$@"; }
install_hold () { apt -yy install --no-install-recommends "$@" && apt-mark hold "$@"; }
install_reinstall () { apt -yy install --reinstall "$@"; }
list_installed_apt () { apt list --installed; }
list_upgrade () { apt list --upgradable; }
only_upgrade () { apt -yy install --no-install-recommends --only-upgrade "$@"; }
only_upgrade_force_overwrite () { apt -yy install --no-install-recommends --only-upgrade -o Dpkg::Options::="--force-overwrite" "$@"; }
pkg_policy () { apt-cache policy "$@"; }
pkg_search () { apt-cache search "$@"; }
purge () { apt -yy purge --remove "$@"; }
purge_autoremove () { apt -yy purge --remove "$@" && apt -yy autoremove "$@"; }
remove () { apt -yy remove "$@"; }
unhold () { apt-mark unhold "$@"; }
update () { apt update; }
upgrade () { apt -yy upgrade "$@"; }
upgrade_downgrades () { apt -yy upgrade --allow-downgrades "$@"; }


# -- Wrap dpkg commands in functions.

dpkg_conf () { dpkg --configure -a; }
dpkg_force_install () { dpkg --force-all -i "$@"; }
dpkg_force_remove () { /usr/bin/dpkg --remove --no-triggers --force-remove-essential --force-bad-path "$@"; }
dpkg_install () { dpkg -i "$@"; }
list_installed_text_start () { dpkg-query -l | less > installed_pkgs_start.txt; }
list_installed_text_end () { dpkg-query -l | less > installed_pkgs_end.txt; }
list_number_pkgs () { dpkg-query -f '${binary:Package}\n' -W | wc -l; }
list_pkgs_size () { dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | head -25 | awk '{print $1/1024, $2}'; }
