#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2018-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#   Copyright <2017-2018> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                            #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

export LANG=C
export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
export PATH=$PATH:/tmp/scripts


# -- Functions.

puts () { printf "\n\n --- %s\n" "$*"; }


#====================	START

puts "STARTING BOOTSTRAP."


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Block installation of some packages.

cp -r /configs/files/apt_preferences/package_preferences /etc/apt/preferences.d/package_preferences
cp -r /configs/files/apt_preferences/repository_preferences /etc/apt/preferences.d/repository_preferences


# -- Make directories in /tmp.

mkdir -p /tmp/{kernel,casper,scripts,pkg-origin}


# -- Copy build scripts.

cp -r /configs/scripts/stages/* /tmp/scripts


# -- Copy pkg-origin to $PATH

cp -r /configs/files/other/pkg-origin /tmp/pkg-origin


# -- Copy apt_config.

cp -r /configs/files/apt_conf/* /etc/apt/apt.conf.d/


###############################
# INFORMATION:                #
# Root content starts here    #
###############################

# -- Check installed packages after adding basic packages to chroot.

list_installed_text_start


# -- Add repositories to build root.

puts "ADDING NITRUX SOURCES."

01-add-nitrux-sources


# -- Add bootloader.

puts "ADDING BOOTLOADER AND SECURE BOOT."

02-install-bootloader


# -- Remove systemd packages.

puts "REMOVE SYSTEMD PACKAGES."

03-remove-systemd-packages


# -- Add OpenRC as init.

puts "ADDING OPENRC."

04-install-openrc


# -- Add casper.

puts "ADDING CASPER."

05-install-casper


# -- Add kernel.

puts "ADDING KERNEL."

06-install-kernel


# -- Add packages from Devuan.

puts "ADDING PACKAGES FROM DEVUAN."

07-install-devuan-packages


# -- Add Nitrux meta-packages.

puts "ADDING NITRUX BASE PACKAGES."

08-install-nitrux-packages


# -- Add Misc. drivers.

puts "ADDING MISC. DRIVERS."

09-install-hw-packages


# -- Add NVIDIA drivers.

puts "ADDING NVIDIA DRIVERS."

10-install-nvidia-drivers


# -- Add NX Desktop meta-package.

puts "ADDING NX DESKTOP."

11-install-desktop-session


# -- Add Calamares.

puts "ADDING CALAMARES INSTALLER."

12-install-calamares


# -- Upgrade MESA packages.

puts "UPGRADE MESA."

13-upgrade-mesa


# -- Add OpenRC configuration.

puts "ADDING OPENRC CONFIG."

14-install-init-config


# -- Add Live user configuration.

puts "ADDING LIVE USER CONFIG."

15-add-live-user


# -- Add initramfs scripts.

puts "ADDING INITRAM SCRIPTS"

16-update-initram-config


# -- Remove sources used to build the root.

puts "REMOVE BUILD SOURCES."

17-remove-build-sources


#################################
# WARNING:                      #
# No apt usage past this point. #
#################################


# -- Changes specific to this image. If they can be put in a package, do so.
# -- FIXME: These fixes should be included in a package.

puts "ADDING MISC. FIXES."

18-add-misc-fixes


# -- Changes specific to this image. If they can be put in a package, do so.
# -- FIXME: These fixes should be included in a package.

puts "EDITING CONF. FILES."

19-edit-conf-files


#############################
# INFORMATION:              #
# Root content ends here    #
#############################

puts "PERFORM MANUAL CHECKS."

20-manual-checks


# -- Create a list of installed packages at end.

list_installed_text_end


puts "EXITING BOOTSTRAP."

#====================	END
