#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2018-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#   Copyright <2017-2018> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                            #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

export LANG=C
export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
export PATH=$PATH:/tmp/iso-tool/stages
export TERM=dumb


# -- Functions.

puts () { printf "\n\n --- %s\n" "$*"; }


#====================	START

puts "STARTING BOOTSTRAP."


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add APT configuration.

cp -r /configs/files/apt_preferences/* /etc/apt/preferences.d/
cp -r /configs/files/apt_conf/* /etc/apt/apt.conf.d/


# -- Create scripts directory in /tmp and move the stages scripts here.

mkdir -p /tmp/iso-tool/stages

cp /configs/scripts/stages/* /tmp/iso-tool/stages


###############################
# INFORMATION:                #
# Root content starts here    #
###############################

# -- Create a list of the installed packages in the rootfs.

list_installed_text_start


# -- Add repositories to build root.

puts "ADDING BUILD SOURCES."

01-add-build-sources


# -- Remove systemd packages.

puts "REMOVE SYSTEMD PACKAGES."

02-remove-systemd-packages


# -- Add bootloader.

puts "ADDING BOOTLOADER AND SECURE BOOT."

03-install-bootloader


# -- Add kernel.

puts "ADDING KERNEL."

04-install-kernel


# -- Add OpenRC as init.

puts "ADDING OPENRC."

05-install-openrc


# -- Add casper.

puts "ADDING CASPER."

06-install-casper


# -- Add Plymouth from Devuan.

puts "ADDING PLYMOUTH FROM DEVUAN."

07-install-bootsplash


# -- Add Nitrux meta-packages.

puts "ADDING NITRUX BASE PACKAGES."

08-install-nitrux-base


# -- Add hardware support.

puts "ADDING HARDWARE SUPPORT."

09-install-hardware-support


# -- Add NVIDIA drivers.

puts "ADDING NVIDIA DRIVERS."

10-install-nvidia-drivers


# -- Add Nitrux Desktop meta-package.

puts "ADDING NITRUX DESKTOP."

11-install-desktop-session


# -- Add Calamares.

puts "ADDING CALAMARES INSTALLER."

12-install-calamares


# -- Add OpenRC configuration.

puts "ADDING OPENRC CONFIG."

13-install-init-config


# -- Add Live user configuration.

puts "ADDING LIVE USER CONFIG."

14-add-live-user


# -- Add initramfs scripts.

puts "ADDING INITRAM SCRIPTS"

15-update-initram-config


#############################
# INFORMATION:              #
# Root content ends here    #
#############################


# -- Create a list of installed packages at after modifying the rootfs.

list_installed_text_end


# -- Remove sources used to build the root.

puts "REMOVE BUILD SOURCES."

16-remove-build-sources


#################################
# WARNING:                      #
# No apt usage past this point. #
#################################


# -- Changes specific to this image. If they can be put in a package, do so.
#    -- Note: These fixes should be included in a package.

puts "ADDING MISC. FIXES."

17-add-misc-fixes


# -- Changes specific to this image. If they can be put in a package, do so.
#    -- Note: These fixes should be included in a package.

puts "EDITING CONF. FILES."

18-edit-conf-files


# -- Check files and directories.

puts "PERFORM MANUAL CHECKS."

19-manual-checks


# -- Create var data archive for NUTS.

puts "CREATE VAR ARCHIVE."

20-create-var-archive


puts "EXITING BOOTSTRAP."

puts ""

#====================	END
