#! /bin/sh

kernel_version="$(uname -r | grep -Eo '[0-9]\.[0-9]*\.[0-9]*')"

kernel_url="https://kernel.org/pub/linux/kernel/v4.x/linux-${kernel_version}.tar.xz"

syslinux_url="https://kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz"

use_old_kernel_config=no
