#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2017-2026 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


set -eu


# -- Prepare the directories for the build. Cleanup previously created build directories.

if ls /tmp/tmp.* 1> /dev/null 2>&1; then
  rm -rf /tmp/tmp.*
fi

build_dir=$(mktemp -d)
iso_dir=$(mktemp -d)
output_dir=$(mktemp -d)

chmod 755 "$build_dir"

config_dir=$PWD/configs


# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$config_dir/scripts/others/apt-funcs"


# -- Build environment stuff.

bash "$config_dir/scripts/stages/00-install-host-packages"


# -- The command "time" is a Bash built-in. However, the package 'time' can be installed to supply this command.

[ "${__time_traced-}" ] || {
    export __time_traced=yes
    /usr/bin/time -f "\nReal Time: %E\nUser Time: %U seconds\nSystem Time: %S seconds\nCPU Usage: %P\nMax Resident Memory: %M KB" "$0" "$@"
    exit
}


# -- Clean up before starting.

if [ -f "$config_dir/rootfs.tar.xz" ] || [ -f "$config_dir/rootfs.tar.gz" ]; then
  rm -f "$config_dir/rootfs.tar.xz" "$config_dir/rootfs.tar.gz"
fi


# -- The name of the ISO image.

image=nitrux-$(git branch --show-current)-$(git rev-parse --short=8 HEAD)-$(uname -m | sed "s/x86_64/amd64/").iso


# -- Download the rootfs and prepare the directory where the filesystem will be created.

base_img_url=https://raw.githubusercontent.com/Nitrux/storage/master/RootFS/Debian/Testing/rootfs.tar.xz

axel -o "$config_dir" -c -n 10 $base_img_url

tar xf "$config_dir/rootfs.tar.xz" -C "$build_dir"


# -- Create a directory to put the build log and the output files.

build_artifacts_dir="$PWD/build-artifacts/${image%.iso}"

iso_tool_bootstrap_log="$build_artifacts_dir/${image%.iso}.bstlog"

mkdir -p "$build_artifacts_dir"


# -- Copy the tooling to a directory in the PATH.

cp "$PWD/tooling/"* /usr/bin/


# -- Build the root.
#    -- Wrap runch and its mount namespace in a subshell.

( < bootstrap \
  unshare --mount -- bash -c 'printf "\n>--- Starting Runch ---\n"; exec runch "$@"' _ \
    -m configs:/configs \
    -r configs \
    "$build_dir" \
    bash ) 2>&1 | sed -E 's/\x1b\[[0-9;]*[a-zA-Z]//g' | tee "$iso_tool_bootstrap_log"

stty sane

sync

echo ""


# -- Get package lists from build directory.

mv "$build_dir"/installed_pkgs_start.txt "$output_dir"/"${image%.iso}.rootfs.buildlist"
mv "$build_dir"/installed_pkgs_end.txt "$output_dir"/"${image%.iso}.buildlist"


# -- Get data archive from build directory.

mv "$build_dir"/var-lib-dpkg-*.tar.xz "$output_dir"


# -- Copy the kernel and initramfs to $iso_dir.
#    -- Note: vmlinuz and initrd are not moved to $iso_dir/; they're left at $build_dir/boot

mkdir -p "$iso_dir"/boot

cp "$(echo "$build_dir"/boot/vmlinuz* | tr " " "\n" | sort | tail -n 1)" "$iso_dir"/boot/kernel
cp "$(echo "$build_dir"/boot/initrd*  | tr " " "\n" | sort | tail -n 1)" "$iso_dir"/boot/initramfs


# -- Create marker file at build time to determine ISO branch.

current_branch=$(git branch --show-current)

if echo "$current_branch" | grep -qi "nvopen"; then
    iso_flavor="ISO_BRANCH=nvopen"
else
    iso_flavor="ISO_BRANCH=mesa"
fi

echo "$iso_flavor" > "$build_dir"/etc/iso-release


# -- Create SquashFS of the root directory.

( while :; do sleep 300; printf ".\n"; done ) &

mkdir -p "$iso_dir"/casper

mksquashfs "$build_dir" "$iso_dir"/casper/filesystem.squashfs \
    -comp zstd \
    -Xcompression-level 18 \
    -b 1M \
    -noappend \
    -quiet \
    -mem 4G


# -- Generate the ISO image.

grub_theme="$config_dir/files/grub_files/theme"

if [ ! -d "$grub_theme/nitrux" ]; then
    echo "Error: GRUB theme directory '$grub_theme/nitrux' not found."
    exit 1
fi

if [ ! -f "$config_dir/files/grub_files/live/grub.cfg" ]; then
    echo "Missing grub.cfg"
    exit 1
fi

if [ ! -f "$config_dir/files/grub_files/live/loopback.cfg" ]; then
    echo "Missing loopback.cfg"
    exit 1
fi

mkiso \
    -V "NITRUX" \
    -e \
    -g "$config_dir/files/grub_files/live/grub.cfg" \
    -g "$config_dir/files/grub_files/live/loopback.cfg" \
    -t "$grub_theme"/nitrux \
    "$iso_dir" "$output_dir/$image"


# -- Calculate the checksum.

sha512sum "$output_dir/$image" | sed "s|$output_dir/||" > "$output_dir/${image%.iso}.sha512"


# -- Move files to specific directory.

mv "$output_dir"/* "$build_artifacts_dir"


# -- Remove the tooling from the PATH.

rm -f /usr/bin/{mkiso,runch} || true 


# -- Clean up build directories.

if ls /tmp/tmp.* 1> /dev/null 2>&1; then
  rm -rf /tmp/tmp.*
fi
