#! /bin/sh

# - - - Colorize messages.

say () { echo -e "\e[32m> \e[0m $@"; }
err () { echo -e "\e[31m# $@ \e[0m"; }


# - - - Where am I?

WD=`pwd`


# - - - Know how and what to build.

. steps/config || { say "Can't continue. No config file found."; exit; }



# - - - Clean the workspace if needed.

if [ "$1" == "clean" ]; then
	rm -rf build/*
	say "Workspace is clean. Creating the new one..."
fi

mkdir -p \
	build/rootfs    \
	build/initramfs \
	build/sources   \
	build/iso


# - - - Download and extract the specified file.

get-file () {
	cd $WD/build/sources

	url=$1
	file=${url##*/}

	say "Downloading $file..."

	if wget --no-clobber -c -q --show-progress $url; then
		case $file in
			*tar.??*)
				say "Extracting $file..."
				tar -xf $file
			;;
		esac
	else
		err "Unable to fetch '$url'."
	fi

	cd $WD
}


# - - - Start the build.

set -e

. steps/kernel
. steps/initramfs
. steps/rootfs
. steps/pack

say "Succesfully built $iso_name"
say "Saved as build/$iso_name.iso"
