#! /bin/sh


_mount () {

	echo test -e "$1" ||
		_e "'$1' does not exist."

	echo mkdir -p "${2%/*}"

	echo test -f "$1" && echo \> "${2%/*}"
	echo test -d "$1" && echo mkdir -p "$2"

	echo mount -B "$1" "$2"

}


_build_dir="tmp-$RANDOM"
_chroot_dir="./configs:$build_dir/configs"
_extra_mount_points="./configs:/configs"

for dir in $_extra_mount_points; do _mount "${dir%%:*}" $_chroot_dir/"${dir##*:}"; done
