#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
prereqs)
       prereqs
       exit 0
       ;;
esac

# shellcheck source=/dev/null
. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

GREETD_CONFIG="/root/etc/greetd/config.toml"

if [ -f "$GREETD_CONFIG" ]; then
    cat >> "$GREETD_CONFIG" <<EOF

[initial_session]
command = "dbus-run-session Hyprland"
user = "$USERNAME"
EOF
fi

log_end_msg
