#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/configs/scripts/others/apt-funcs


# -- Install packages for host.

update

HOST_PKGS='
	axel
	dkms
	mokutil
	shim-signed
	squashfs-tools
	time
'

XORRISO_PKGS='
	libburn4
	libisoburn1
	libisofs6
	libjte2
	mtools
	sshpass
	xorriso
'

GRUB_PKGS='
	grub-efi-amd64
	grub-efi-amd64-signed
	grub-pc-bin
'

install $HOST_PKGS $XORRISO_PKGS $GRUB_PKGS
