#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/configs/scripts/others/apt-funcs


# -- Update hosts' package index.

update


# -- Define an array of packages for the host.

INSTALL_HOST_PKGS=(
    axel
    grub-efi-amd64
    squashfs-tools
    time
    xorriso
)


# -- Install packages for host.

install "${INSTALL_HOST_PKGS[@]}"
