#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source "$PWD"/configs/scripts/others/apt-funcs

HOST_PKGS='
	axel
	dkms
	mokutil
	shim-signed
	squashfs-tools
'

XORRISO_PKGS='
	libburn4
	libisoburn1
	libisofs6
	libjte2
	mtools
	sshpass
	xorriso
'

GRUB_PKGS='
	grub-efi-amd64
	grub-efi-amd64-signed
	grub-pc-bin
'

update
install $HOST_PKGS $XORRISO_PKGS $GRUB_PKGS
