#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add Nitrux repository keys.

add_nitrux_key depot
add_nitrux_key unison
add_nitrux_key testing
add_nitrux_key area51
add_nitrux_key skidrow
add_nitrux_key mauikit


# -- Add third-party repository keys.

add_third_party_repo_keys \
	8BC44DF02642485FF1F3CC04AB78C60DFB581603 \
	7CE0331F71E0A238BB1002D70E406D181DCEE19C > /dev/null


# -- Add Nitrux repositories.

cp /configs/files/sources/sources.list.nitrux /etc/apt/sources.list
cp /configs/files/sources/sources.list.nitrux.testing /etc/apt/sources.list.d/nitrux-testing-repo.list
cp /configs/files/sources/sources.list.nitrux.area51 /etc/apt/sources.list.d/nitrux-area51-repo.list
cp /configs/files/sources/sources.list.nitrux.skidrow /etc/apt/sources.list.d/nitrux-skidrow-repo.list
cp /configs/files/sources/sources.list.nitrux.mauikit /etc/apt/sources.list.d/nitrux-mauikit-repo.list


# -- Add Debian repository.

cp /configs/files/sources/sources.list.debian.testing /etc/apt/sources.list.d/debian-testing-repo.list


# -- Add third-party repositories.

cp /configs/files/sources/sources.list.pika-os /etc/apt/sources.list.d/pika-os-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list


update


# -- Use the APT package from Devuan because Debian had the wisdom of adding libsystemd0 as a fkn dependency because why tf not, right?

DEVUAN_PKGMAN_PKGS='
	apt/forky
	libapt-pkg7.0/forky
'


install $DEVUAN_PKGMAN_PKGS


# -- Update Git.

UPDATE_GIT_PKGS='
	git
	git-man
'

only_upgrade $UPDATE_GIT_PKGS
