#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Install basic packages.

update
upgrade

CHROOT_BASIC_PKGS='
	apt-transport-https
	apt-utils
	appstream
	axel
	curl
	dirmngr
	gnupg2
	libzstd-dev
	less
	lz4
	perl-modules-5.36
	zstd
'

install $CHROOT_BASIC_PKGS
