#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install basic packages.

update

CHROOT_BASIC_PKGS='
	apt-transport-https
	axel
	curl
	dirmngr
	git
	gnupg2
	libzstd-dev
	less
	lz4
	perl-modules-5.38
	zstd
'

install $CHROOT_BASIC_PKGS
