#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Add repository keys.

add_nitrux_key_depot
add_nitrux_key_unison
add_nitrux_key_testing
add_nitrux_key_area51


#	Add repository sources.

cp /configs/files/sources/sources.list.nitrux /etc/apt/sources.list
cp /configs/files/sources/sources.list.nitrux.testing /etc/apt/sources.list.d/nitrux-testing-repo.list
cp /configs/files/sources/sources.list.nitrux.area51 /etc/apt/sources.list.d/nitrux-area51-repo.list
cp /configs/files/sources/sources.list.debian.testing /etc/apt/sources.list.d/debian-testing-repo.list


update
