#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Specify the packages from Devuan because Debian made libsystemd0 mandatory for APT, PAM, login, bsdutils, coreutils, and procps for no reason since neither truly requires it (because why not, right?).

INSTALL_DEVUAN_APT_PKGS=(
    apt/duke
    libapt-pkg7.0/duke
)

INSTALL_DEVUAN_UTILS_PKGS=(
    bsdutils/duke
    coreutils/duke
    login/duke
    mount/duke
    util-linux/duke
    procps/duke
)

INSTALL_DEVUAN_UDEV_PKGS=(
    eudev/duke
    udev/duke
    libudev1/duke
)

INSTALL_DEVUAN_PAM_PKGS=(
    libpam-modules/duke
    libpam-modules-bin/duke
    libpam-runtime/duke
    libpam0g/duke
)

INSTALL_DEVUAN_ELOGIND_PKGS=(
    elogind/duke
)

INSTALL_DEVUAN_DBUS_PKGS=(
    dbus/duke
    dbus-daemon/duke
)

install_downgrades "${INSTALL_DEVUAN_APT_PKGS[@]}" "${INSTALL_DEVUAN_UTILS_PKGS[@]}" "${INSTALL_DEVUAN_UDEV_PKGS[@]}" "${INSTALL_DEVUAN_PAM_PKGS[@]}" "${INSTALL_DEVUAN_ELOGIND_PKGS[@]}" "${INSTALL_DEVUAN_DBUS_PKGS[@]}"


# -- Remove libsystemd0 from the rootfs.

REMOVE_SYSTEMD_PKGS=(
    libsystemd0
)

dpkg_force_remove "${REMOVE_SYSTEMD_PKGS[@]}"


# -- Add docker-systemctl-replacement to make maintainer scripts shut up about it.

INSTALL_DOCKER_SYSTEMCTL_PKG=(
    systemctl
)

install "${INSTALL_DOCKER_SYSTEMCTL_PKG[@]}"


# -- Fix the warnings (SyntaxWarning: invalid escape sequence '\w') in https://github.com/gdraheim/docker-systemctl-replacement due to unescaped regex backslashes in normal string literals in Python.
#    -- Python 3.12+ warns about these because "\w" is interpreted as a string escape (which is undefined), not a regex pattern.

sed -i -E 's/re\.sub\("([^"]*\\w[^"]*)"/re.sub(r"\1"/g' /usr/bin/systemctl
