#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add eudev and mount from Devuan.
# -- Specify these packages because Debian made libsystemd0 mandatory for PAM, login, bsdutils, and coreutils for no reason since neither requires it. Also, mount is broken or something? *sigh*

INSTALL_DEVUAN_UTILS_PKGS=(
	bsdutils/duke
	coreutils/duke
	login/duke
	mount/duke
	util-linux/duke
)

INSTALL_DEVUAN_UDEV_PKGS=(
	eudev/duke
	udev/duke
)

INSTALL_DEVUAN_PAM_PKGS=(
	libpam-modules/duke
	libpam-modules-bin/duke
	libpam-runtime/duke
	libpam0g/duke
)

install "${INSTALL_DEVUAN_UTILS_PKGS[@]}" "${INSTALL_DEVUAN_UDEV_PKGS[@]}" "${INSTALL_DEVUAN_PAM_PKGS[@]}"


# -- Remove libsystemd0.

REMOVE_SYSTEMD_PKGS=(
	libsystemd0
)

remove "${REMOVE_SYSTEMD_PKGS[@]}"


# -- Add elogind from Devuan.

INSTALL_DEVUAN_ELOGIND_PKGS='
	elogind/duke
'

install "${INSTALL_DEVUAN_ELOGIND_PKGS[@]}"


# -- Add docker-systemctl-replacement to make maintainer scripts shut up about it.

INSTALL_DOCKER_SYSTEMCTL_PKG='
	systemctl
'

install "${INSTALL_DOCKER_SYSTEMCTL_PKG[@]}"


# -- Fix the warnings (SyntaxWarning: invalid escape sequence '\w') in https://github.com/gdraheim/docker-systemctl-replacement due to unescaped regex backslashes in normal string literals in Python.
# -- Python 3.12+ warns about these because "\w" is interpreted as a string escape (which is undefined), not a regex pattern.

sed -i -E 's/re\.sub\("([^"]*\\w[^"]*)"/re.sub(r"\1"/g' /usr/bin/systemctl
