#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Downgrade PAM packages because 1) Newer packages depend on libsystemd0 (why?) and 2) Newer packages (1.5.3-7) break something that causes kscreenlocker not to accept the password to unlock the session.

DOWNGRADE_PAM_PKGS='
	libpam-modules=1.5.2-6+deb12u1
	libpam-modules-bin=1.5.2-6+deb12u1
	libpam-runtime=1.5.2-6+deb12u1
	libpam0g=1.5.2-6+deb12u1
'

install_downgrades_hold $DOWNGRADE_PAM_PKGS


# -- Add eudev and mount from Devuan.
# -- Specify our packages because Debian decided to make libsystemd mandatory for PAM and login for no reason since neither requires it. Also, mount is broken or something? *sigh*

DEVUAN_EUDEV_PKGS='
	eudev
	login=1:4.15.2-4+nitrux
	mount/forky
	udev/forky
	util-linux/forky
'

install $DEVUAN_EUDEV_PKGS


# -- Remove libsystemd0.

REMOVE_SYSTEMD_PKGS='
	systemd
	systemd-sysv
	libsystemd0
'

dpkg_force_remove $REMOVE_SYSTEMD_PKGS


# -- Add standalone systemctl to make most of the maintainer scripts in the packages stfu about it.

SYSTEMCTL_STANDALONE_PKG='
	systemctl
'

install $SYSTEMCTL_STANDALONE_PKG
