#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Upgrade package manager.

DEVUAN_PKGMAN_PKGS='
	apt
	dpkg
'

install_hold $DEVUAN_PKGMAN_PKGS
