#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Upgrade dpkg for zstd support.

UPGRADE_DPKG='
	dpkg=1.21.1ubuntu1
'

install_downgrades $UPGRADE_DPKG


#	Do dist-upgrade.

dist_upgrade
