#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Add bootloader
#
#	The GRUB2 packages from Debian do not work correctly with EFI.

GRUB2_PKGS='
	grub-common=2.06-2ubuntu18
	grub-efi-amd64=2.06-2ubuntu17
	grub-efi-amd64-bin=2.06-2ubuntu17
	grub-efi-amd64-signed=1.193+2.06-2ubuntu17
	grub-pc-bin=2.06-2ubuntu18
	grub2-common=2.06-2ubuntu18
	libfreetype6/testing
'

install $GRUB2_PKGS


#	Add packages for secure boot compatibility.

SB_SHIM_PKGS='
	sbsigntool=0.9.4-2ubuntu2
	shim-signed=1.51+15.4-0ubuntu9
	mokutil=0.4.0-1ubuntu2
'

install $SB_SHIM_PKGS
