#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Add bootloader
#
#	The GRUB2 packages from Debian do not work correctly with EFI.

GRUB2_PKGS='
	grub-common=2.12~rc1-10ubuntu4
	grub-efi-amd64=2.12~rc1-10ubuntu4
	grub-efi-amd64-bin=2.12~rc1-10ubuntu4
	grub-efi-amd64-signed=1.197+2.12~rc1-10ubuntu4
	grub-pc-bin=2.12~rc1-10ubuntu4
	grub2-common=2.12~rc1-10ubuntu4
'

install $GRUB2_PKGS


#	Add packages for secure boot compatibility.

SB_SHIM_PKGS='
	mokutil=0.6.0-2
	sbsigntool=0.9.4-3.1ubuntu3
	shim-signed=1.56+15.7-0ubuntu1
'

install $SB_SHIM_PKGS
