#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install a kernel.

DEFAULT_KERNEL_PKG='
	linux-headers-6.15.6-pikaos
	linux-image-6.15.6-pikaos
'

EXTRA_KERNEL_PKGS='
	binutils
	binutils-common
	binutils-x86-64-linux-gnu
	clang
	clang-19
	gcc-15-base
	kernel-pika-config
	libasan8
	libatomic1
	libbabeltrace1
	libbinutils
	libc-dev-bin
	libc6-dev
	libclang-cpp19
	libclang1-19
	libcpupower1
	libcrypt-dev
	libctf-nobfd0
	libctf0
	libcurl4t64
	libdebuginfod-common
	libdebuginfod1t64
	libdw1t64
	libedit2
	libelf1t64
	libgc1
	libglib2.0-0t64
	libgomp1
	libgprofng0
	libhwasan0
	libitm1
	libjansson4
	libjson-c5
	libllvm19
	liblsan0
	libnl-3-200
	libnl-genl-3-200
	libnuma1
	libobjc-14-dev
	libobjc4
	libopencsd1
	libpci3
	libpfm4
	libpython3.13
	libquadmath0
	libsframe1
	libslang2
	libtraceevent1
	libtsan2
	libubsan1
	libunwind8
	libxml2
	libz3-4
	linux-cpupower
	linux-libc-dev
	linux-perf
	lld
	lld-19
	llvm
	llvm-19
	llvm-19-linker-tools
	llvm-19-runtime
	llvm-runtime
	pci.ids
	rpcsvc-proto
	scx
'

install $DEFAULT_KERNEL_PKG $EXTRA_KERNEL_PKGS
