#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add a default kernel.

INSTALL_KERNEL_PKGS=(
    linux-nitrux-amd64
)

install "${INSTALL_KERNEL_PKGS[@]}"
