#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Delete these SysV scripts, otherwise they cause conflicts when updating the service dependencies.
#    -- OpenRC explicitly disallows a service from being both:
#       -- A real service (defined by /etc/init.d/<name>)
#       -- And providing a virtual service of the same name (via provide <name>)

DELETE_SYSV_SCRIPTS=(
    acpi-support
    acpid
    apparmor
    bluetooth
    console-setup.sh
    cron
    cryptdisks
    cryptdisks-early
    dbus
    elogind
    eudev
    greetd
    keyboard-setup.sh
    plymouth
    plymouth-log
    procps
    rsyslog
    sddm
    sudo
    udev
    uuidd
)

rm -f "${DELETE_SYSV_SCRIPTS[@]/#//etc/init.d/}"


# -- Add Debian-flavored OpenRC to use it as the init system. Ensure /run/openrc exists before installing the package, because apparently it doesn't sometimes.

mkdir -p /run/openrc

INSTALL_OPENRC_PKGS=(
    openrc
)

install "${INSTALL_OPENRC_PKGS[@]}"
