#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add OpenRC as init.

OPENRC_INIT_PKGS='
	initscripts
	openrc
	policycoreutils
'

install $OPENRC_INIT_PKGS
