#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add casper for the Live session.

INSTALL_CASPER_PKGS=(
    casper/duke
    eject/duke
    fdisk/duke
    uuid-runtime/duke
)

install "${INSTALL_CASPER_PKGS[@]}" 
