#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Use the packages for Plymouth from Devuan because these don't require libsystemd0.

INSTALL_DEVUAN_PLYMOUTH_PKGS=(
    plymouth/duke
    plymouth-label/duke
)

install "${INSTALL_DEVUAN_PLYMOUTH_PKGS[@]}"
