#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Add casper.

CASPER_DEPS_PKGS='
	casper=1.486
	initramfs-tools=0.142ubuntu15.1
	initramfs-tools-bin=0.142ubuntu15.1
	initramfs-tools-core=0.142ubuntu15.1
'

install $CASPER_DEPS_PKGS


#	Hold initramfs and casper packages.

INITRAMFS_CASPER_PKGS='
	casper
	initramfs-tools
	initramfs-tools-core
	initramfs-tools-bin
'

hold $INITRAMFS_CASPER_PKGS
