#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add casper.
#
# -- We have to specify to APT the "udev" package to use; otherwise, it just uses whatever the fck it wants, even if the package is from a repository with
# -- a higher priority and we blocked the origin of the version we don't want.

CASPER_DEPS_PKGS='
	udev/forky
'

CASPER_PKGS='
	casper
'

install $CASPER_DEPS_PKGS && install_hold $CASPER_PKGS
