#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	9AE4078033F8024D > /dev/null

cp /configs/files/sources/sources.list.liquorix /etc/apt/sources.list.d/liquorix-repo.list

update

DEFAULT_KERNEL_PKG='
	linux-image-liquorix
	libcrypt-dev/trixie
	libcrypt1/trixie
'

DEBIAN_KERNEL_PKG='
	linux-image-amd64/unstable
	linux-headers-amd64/unstable
'

install_downgrades $DEFAULT_KERNEL_PKG $DEBIAN_KERNEL_PKG

rm \
	/etc/apt/sources.list.d/liquorix-repo.list

remove_repo_keys \
	9AE4078033F8024D > /dev/null

update
