#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install the kernel.

add_repo_keys \
	9AE4078033F8024D > /dev/null

cp /configs/files/sources/sources.list.liquorix /etc/apt/sources.list.d/liquorix-repo.list

update

DEFAULT_KERNEL_PKG='
	linux-image-liquorix
'

install $DEFAULT_KERNEL_PKG

rm \
	/etc/apt/sources.list.d/liquorix-repo.list

remove_repo_keys \
	9AE4078033F8024D > /dev/null

update
