#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install Nitrux base packages and use the packages for PolicyKit from Devuan because these don't require libsystemd0.

INSTALL_NITRUX_BASE_PKGS=(
    base-files
    nitrux-minimal
    nitrux-standard
)

INSTALL_DEVUAN_POLICYKIT_PKGS=(
    libpam-elogind/duke
    libpolkit-agent-1-0/duke
    libpolkit-gobject-elogind-1-0/duke
    libpolkit-qt6-1-1/duke
    pkexec/duke
    polkitd/duke
)

install "${INSTALL_NITRUX_BASE_PKGS[@]}" "${INSTALL_DEVUAN_POLICYKIT_PKGS[@]}"
