#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

cp /configs/files/sources/sources.list.devuan.excalibur /etc/apt/sources.list.d/devuan-excalibur-repo.list

update

DEVUAN_PLYMOUTH_PKGS='
	plymouth/excalibur
	plymouth-label/excalibur
	plymouth-x11/excalibur
	libcairo-gobject2/excalibur
	libcairo2/excalibur
'

install $DEVUAN_PLYMOUTH_PKGS

rm \
	/etc/apt/sources.list.d/devuan-excalibur-repo.list

remove_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

update
