#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Use the packages for Plymouth, NetworkManager and PolicyKit from Devuan because these don't require Systemd.

DEVUAN_PLYMOUTH_PKGS='
	plymouth
	plymouth-label
	plymouth-x11
'

install_downgrades $DEVUAN_PLYMOUTH_PKGS

DEVUAN_POLKIT_PKGS='
	libpam-elogind
	libpolkit-agent-1-0
	libpolkit-gobject-1-0
	libpolkit-gobject-elogind-1-0
	policykit-1
	pkexec
	polkitd
'

DEVUAN_NM_PKGS='
	network-manager
'

install_downgrades $DEVUAN_POLKIT_PKGS $DEVUAN_NM_PKGS
