#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

cp /configs/files/sources/sources.list.devuan.ceres /etc/apt/sources.list.d/devuan-ceres-repo.list

update

DEVUAN_PLYMOUTH_PKGS='
	plymouth/ceres
	plymouth-label/ceres
	plymouth-x11/ceres
	libcairo-gobject2/ceres
	libcairo2/ceres
'

install $DEVUAN_PLYMOUTH_PKGS

rm \
	/etc/apt/sources.list.d/devuan-ceres-repo.list

remove_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

update
