#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

cp /configs/files/sources/sources.list.devuan.excalibur /etc/apt/sources.list.d/devuan-excalibur-repo.list

update

DEVUAN_POLKIT_PKGS='
	libpam-elogind/excalibur
	libpolkit-agent-1-0/excalibur
	libpolkit-gobject-1-0/excalibur
	libpolkit-gobject-elogind-1-0/excalibur
	policykit-1/excalibur
	pkexec/excalibur
	polkitd/excalibur
'

install $DEVUAN_POLKIT_PKGS

rm \
	/etc/apt/sources.list.d/devuan-excalibur-repo.list

remove_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

update
