#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install NVIDIA packages from PikaOS repository because the driver requires the same compiler as the kernel and that kernel uses LLVM and CLang.

NV_PIKA_PKGS='
	autoconf
	automake
	autopoint
	autotools-dev
	debhelper
	dh-autoreconf
	dh-strip-nondeterminism
	dwz
	firmware-nvidia-gsp-570
	gettext
	glx-alternative-mesa
	glx-alternative-nvidia
	glx-diversions
	intltool-debian
	libarchive-zip-perl
	libcuda1-570
	libcudadebugger1-570
	libdebhelper-perl
	libegl-nvidia0-570
	libfile-stripnondeterminism-perl
	libgl1-nvidia-glvnd-glx-570
	libgles-nvidia1-570
	libgles-nvidia2-570
	libgles1
	libglx-nvidia0-570
	libnvcuvid1-570
	libnvidia-allocator1-570
	libnvidia-api1-570
	libnvidia-cfg1-570
	libnvidia-egl-gbm1
	libnvidia-eglcore-570
	libnvidia-encode1-570
	libnvidia-fbc1-570
	libnvidia-glcore-570
	libnvidia-glvkspirv-570
	libnvidia-gpucomp-570
	libnvidia-ml1-570
	libnvidia-ngx1-570
	libnvidia-nvvm4-570
	libnvidia-opticalflow1-570
	libnvidia-pkcs11-openssl3-570
	libnvidia-ptxjitcompiler1-570
	libnvidia-rtcore-570
	libnvidia-vksc-core-570
	libnvoptix1-570
	libtool
	m4
	module-assistant
	nvidia-alternative-570
	nvidia-cuda-mps-570
	nvidia-driver-bin-570
	nvidia-driver-libs-570
	nvidia-egl-common-570
	nvidia-egl-icd-570
	nvidia-kernel-support-570
	nvidia-modprobe-570
	nvidia-open-driver-570
	nvidia-open-kernel-common-570
	nvidia-open-kernel-dkms-570
	nvidia-open-kernel-source-570
	nvidia-opencl-common-570
	nvidia-opencl-icd-570
	nvidia-persitenced-570
	nvidia-powerd-570
	nvidia-settings-570
	nvidia-smi-570
	nvidia-support-570
	nvidia-suspend-common-570
	nvidia-vdpau-driver-570
	nvidia-vulkan-common-570
	nvidia-vulkan-icd-570
	nvidia-xconfig-570
	po-debconf
	update-glx
'

install $NV_PIKA_PKGS
