#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install the NVIDIA proprietary driver using the official installer.
# -- Trying to add the PPA now causes the package manager to do nothing when building the ISO, so thank you, APT! /s.

# -- Download the driver directly from NVIDIA.

BASE_URL="http://download.nvidia.com/XFree86/Linux-x86_64/"
USER_AGENT="BrightSign/8.2.55.5 (XT1144) Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36"
DESTINATION="$(mktemp -d)"
NV_INST_VER="560.28.03"

LATEST_FILE="$NV_INST_VER $NV_INST_VER/NVIDIA-Linux-x86_64-$NV_INST_VER.run"
FILE_PATH="$(echo "$LATEST_FILE" | awk '{print $2}')"
FULL_URL="${BASE_URL}${FILE_PATH}"

axel -a -q -k -U "$USER_AGENT" -n 8 "$FULL_URL" -o "${DESTINATION}/$(basename "$FILE_PATH")"


# -- Install the build dependencies.

NVIDIA_DRV_BUILD_PKGS='
	build-essential
	libglvnd-core-dev
	libglvnd-dev
	pkgconf
'

install $NVIDIA_DRV_BUILD_PKGS


# -- Execute the installer.

chmod +x "$DESTINATION"/*
for NV_DRV_RUN in "$DESTINATION"/*; do
    if [ -x "$NV_DRV_RUN" ]; then
        "$NV_DRV_RUN" --dkms -s
    fi
done


# -- Blacklist the Nouveau driver if not already blacklisted.

if ! grep -q "^blacklist nouveau$" /etc/modprobe.d/blacklist.conf; then
    printf '%s\n' "blacklist nouveau" >> /etc/modprobe.d/blacklist.conf
fi


# -- Remove build dependencies.

NVIDIA_DRV_DEL_PKGS='
	libglvnd-core-dev
	libglvnd-dev
	pkgconf
	pkgconf-bin
'

purge_autoremove $NVIDIA_DRV_DEL_PKGS


# -- Install additional packages for the NVIDIA proprietary driver which are not part of the installer.

NVIDIA_EXTRA_PKGS='
	nvidia-prime
	screen-resolution-extra
'

install $NVIDIA_EXTRA_PKGS
