#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

cp /configs/files/sources/sources.list.devuan.ceres /etc/apt/sources.list.d/devuan-ceres-repo.list

update

DEVUAN_POLKIT_PKGS='
	libpam-elogind/ceres
	libpolkit-agent-1-0/ceres
	libpolkit-gobject-1-0/ceres
	libpolkit-gobject-elogind-1-0/ceres
	policykit-1/ceres
	pkexec/ceres
	polkitd/ceres
'

install $DEVUAN_POLKIT_PKGS

rm \
	/etc/apt/sources.list.d/devuan-ceres-repo.list

remove_repo_keys \
	541922FB \
	61FC752C \
	D104092C > /dev/null

update
