#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install desktop packages and use the packages for NetworkManager from Devuan because these don't require libsystemd0.

INSTALL_DESKTOP_PKGS=(
    bluedevil
    bluetooth-openrc
    breeze-gtk-theme
    crystal-dock
    dbus-openrc
    desktop-file-utils
    dialog
    dnsmasq
    elogind-openrc
    eudev-openrc
    fonts-nitrux-desktop
    greetd-qtgreet
    greetd-qtgreet-settings
    grim
    hyprland-core
    kgpg
    layer-shell-qt
    libkf6kcmutils-bin
    libnotify-bin
    libpam-pwquality
    libqt6quickcontrols2-6
    libqt6quickshapes6
    libqt6quicktemplates2-6
    libqt6quickwidgets6
    libqt6sql6
    libqt6sql6-sqlite
    libqt6waylandcompositor6
    libqt6wlshellintegration6
    libspa-0.2-bluetooth
    luv-icon-theme
    micro
    network-manager-openrc
    nitrux-desktop-settings
    nitrux-wallpapers
    ntpsec-openrc
    nwg-look
    ocean-sound-theme
    overlayroot
    patchelf
    pciutils
    pinentry-qt
    pipewire
    pipewire-pulse
    pipx
    plasma-nm
    plasma-pa
    plasma-workspace
    plymouth-openrc
    plymouth-theme-nitrux
    polkit-kde-agent-1
    polkitd-openrc
    power-profiles-daemon
    power-profiles-daemon-openrc
    psmisc
    qml6-module-org-kde-kirigami
    qml6-module-qtquick-controls
    qml6-module-qtquick-layouts
    qml6-module-qtquick-shapes
    qml6-module-qtquick-templates
    qml6-module-qtquick-window
    qt6-svg-plugins
    qt6-wayland
    rsyslog-openrc
    rsyslog/duke
    slurp
    sudo-openrc
    sway-notification-center
    systemsettings
    waybar
    wireplumber
    wl-clipboard
    wlogout
    wofi
    wpasupplicant
    x11-utils
    x11-xserver-utils
    xdg-desktop-portal-gtk
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-kde
    xdg-user-dirs
    xdg-utils
    xserver-xorg-legacy
    xsettingsd
    xwaylandvideobridge
    zsh
    ufw
)

INSTALL_DESKTOP_APPS=(
    ark
    corectrl
)

INSTALL_DEVUAN_NM_PKGS=(
    network-manager/duke
)

install "${INSTALL_DESKTOP_PKGS[@]}" "${INSTALL_DESKTOP_APPS[@]}" "${INSTALL_DEVUAN_NM_PKGS[@]}" 
