#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install desktop packages and use the packages for NetworkManager from Devuan because these don't require libsystemd0.

INSTALL_DESKTOP_PKGS=(
    nitrux-desktop
    rsyslog/duke
)

INSTALL_DESKTOP_APPS=(
    nitrux-desktop-apps
    maui-apps
)

INSTALL_DEVUAN_NM_PKGS=(
    network-manager/duke
    network-manager-tui/duke
)

install "${INSTALL_DESKTOP_PKGS[@]}" "${INSTALL_DESKTOP_APPS[@]}" "${INSTALL_DEVUAN_NM_PKGS[@]}"


# -- Divert Evolution files (Why are they even installed?)

dpkg_divert /usr/share/dbus-1/services/org.gnome.evolution.dataserver.Sources5.service.bak /usr/share/dbus-1/services/org.gnome.evolution.dataserver.Sources5.service
dpkg_divert /usr/share/dbus-1/services/org.gnome.evolution.dataserver.AddressBook10.service.bak /usr/share/dbus-1/services/org.gnome.evolution.dataserver.AddressBook10.service
