#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install desktop packages and use the packages for NetworkManager from Devuan because these don't require libsystemd0.

INSTALL_DESKTOP_PKGS=(
    nitrux-desktop
    rsyslog/duke
)

INSTALL_DESKTOP_APPS=(
    nitrux-desktop-apps
    maui-apps
)

INSTALL_DEVUAN_NM_PKGS=(
    network-manager/duke
)

install "${INSTALL_DESKTOP_PKGS[@]}" "${INSTALL_DESKTOP_APPS[@]}" "${INSTALL_DEVUAN_NM_PKGS[@]}" 
