#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	1118213C > /dev/null

cp /configs/files/sources/sources.list.gpu.ppa /etc/apt/sources.list.d/gpu-ppa-repo.list

update


#	Install the NVIDIA driver.

NVIDIA_DRV_PKGS='
	nvidia-driver-550
	nvidia-kernel-source-550
	nvidia-settings
	nvidia-prime
'

NVIDIA_SUPPORTING_LIBS='
	libnvidia-egl-wayland1
'

install $NVIDIA_DRV_PKGS $NVIDIA_SUPPORTING_LIBS


rm \
	/etc/apt/sources.list.d/gpu-ppa-repo.list

remove_repo_keys \
	1118213C > /dev/null

update
