#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


NITRUX_BASE_PKGS='
	base-files=2023.8.27+nitrux-legacy
	nitrux-minimal-legacy
	nitrux-standard-legacy
'

NITRUX_HW_PKGS='
	nitrux-hardware-drivers-legacy
	broadcom-sta-dkms
	displaylink-driver
'

install_downgrades $NITRUX_BASE_PKGS $NITRUX_HW_PKGS
