#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# # -- Install the NVIDIA proprietary driver using the official installer.
# # -- Trying to add the PPA now causes the package manager to do nothing when building the ISO, so thank you, APT! /s.

# # -- Download the driver directly from NVIDIA.

# BASE_URL="http://download.nvidia.com/XFree86/Linux-x86_64/"
# USER_AGENT="BrightSign/8.2.55.5 (XT1144) Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36"
# DESTINATION="$(mktemp -d)"
# NV_INST_VER="555.58.02"

# LATEST_FILE="$NV_INST_VER $NV_INST_VER/NVIDIA-Linux-x86_64-$NV_INST_VER.run"
# FILE_PATH="$(echo "$LATEST_FILE" | awk '{print $2}')"
# FULL_URL="${BASE_URL}${FILE_PATH}"

# axel -a -q -k -U "$USER_AGENT" -n 8 "$FULL_URL" -o "${DESTINATION}/$(basename "$FILE_PATH")"


# # -- Install the build dependencies.

# NVIDIA_DRV_BUILD_PKGS='
# 	build-essential
# 	libglvnd-core-dev
# 	libglvnd-dev
# 	pkgconf
# '

# install $NVIDIA_DRV_BUILD_PKGS


# # -- Execute the installer.

# chmod +x "$DESTINATION"/*
# for NV_DRV_RUN in "$DESTINATION"/*; do
#     if [ -x "$NV_DRV_RUN" ]; then
#         "$NV_DRV_RUN" --dkms -s
#     fi
# done


# # -- Blacklist the Nouveau driver if not already blacklisted.

# if ! grep -q "^blacklist nouveau$" /etc/modprobe.d/blacklist.conf; then
#     printf '%s\n' "blacklist nouveau" >> /etc/modprobe.d/blacklist.conf
# fi


# # -- Remove build dependencies.

# NVIDIA_DRV_DEL_PKGS='
# 	libglvnd-core-dev
# 	libglvnd-dev
# 	pkgconf
# 	pkgconf-bin
# '

# purge_autoremove $NVIDIA_DRV_DEL_PKGS


# # -- Install additional packages for the NVIDIA proprietary driver which are not part of the installer.

# NVIDIA_EXTRA_PKGS='
# 	nvidia-prime
# 	screen-resolution-extra
# '

# install $NVIDIA_EXTRA_PKGS


# -- Install the Bouveau driver.

DIET_NV_DRV_PKGS='
	libdrm-nouveau2
	nouveau-firmware
'

install $DIET_NV_DRV_PKGS
