#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


NITRUX_BASE_PKGS='
	base-files=13.1.34+nitrux-legacy
	nitrux-minimal-legacy
	nitrux-standard-legacy
'

NITRUX_HW_PKGS='
	nitrux-hardware-drivers-legacy
	broadcom-sta-dkms
'
pkg_policy python3-pyqt5 python3-dbus.mainloop.pyqt5
install $NITRUX_BASE_PKGS $NITRUX_HW_PKGS