#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


NITRUX_BASE_PKGS='
	base-files=2023.10.17+nitrux-legacy
	nitrux-minimal-legacy
	nitrux-standard-legacy
'

NITRUX_HW_PKGS='
	nitrux-hardware-drivers-legacy
'

install $NITRUX_BASE_PKGS $NITRUX_HW_PKGS hplip dkms
