#! /bin/bash

set -u

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


MISC_HW_PKGS='
	displaylink-driver
'

install $MISC_HW_PKGS
fix_install
