#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Create this directory otherwise the package displaylink-driver just fkn dies.

mkdir -p /lib/systemd/system-sleep

MISC_HW_PKGS='
	broadcom-sta-dkms
	displaylink-driver
'

install $MISC_HW_PKGS
