#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add Live user.

INSTALL_LIVE_USER=(
    nitrux-live-user
)

install "${INSTALL_LIVE_USER[@]}" 


# -- Replace upstream's 15autologin to enable autologin in casper for the Live user.

cat /configs/files/casper_files/15autologin > /usr/share/initramfs-tools/scripts/casper-bottom/15autologin


# -- Define the desired session in SDDM for the Live user. Since casper is an Ubuntu project, it caters to their flavors, which use Plasma.
#    -- This section is irrelevant if using greetd instead of SDDM.

# LIVE_SESSION="Hyprland.desktop"

# sed -i "s/plasma.desktop/${LIVE_SESSION}/" /usr/share/initramfs-tools/scripts/casper-bottom/15autologin


# -- Replace upstream's 12fstab to enable aesthethic FHS for the Live user.

cat /configs/files/casper_files/12fstab > /usr/share/initramfs-tools/scripts/casper-bottom/12fstab


# -- Replace upstream's 25adduser so casper doesn't blank our damn password.

cat /configs/files/casper_files/25adduser > /usr/share/initramfs-tools/scripts/casper-bottom/25adduser
