#! /bin/bash

set -xe

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D \
	90E51522 > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
'

MISC_DESKTOP_PKGS='
	kde-config-fcitx5/trixie
	kwin-bismuth/trixie
	kwin-x11/jammy
	libjpeg-turbo8/trixie
	libpinyin-data/trixie
	libpinyin13/trixie
	libpoppler-cpp0v5/jammy
	libpoppler-qt5-1/jammy
	libpoppler126/jammy
	maliit-keyboard/jammy
	poppler-utils/jammy
	wireguard/trixie
	dbab
	ch-mount
'

DBGSYM_PACKAGES='
	calamares-dbgsym
	kwin-common-dbgsym
	kwin-x11-dbgsym
	latte-dock-dbgsym
	libkwineffects14-dbgsym
	libkwinglutils14-dbgsym
	libqt5core5a-dbgsym
	libqt5dbus5-dbgsym
	libqt5gui5-dbgsym
	libqt5qml5-dbgsym
	libqt5quick5-dbgsym
	libqt5widgets5-dbgsym
	print-manager-dbgsym
	qml-module-org-kde-kwindowsystem-dbgsym
'

install $NX_DESKTOP_PKG $MISC_DESKTOP_PKGS $DBGSYM_PACKAGES


rm \
	/etc/apt/sources.list.d/neon-user-repo.list \
	/etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	55751E5D \
	90E51522 > /dev/null

update
