#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D \
	90E51522 > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
'

UNISON_DESKTOP_PKGS='
	kde-config-fcitx5/trixie
	kwin-bismuth/trixie
	kwin-x11/jammy
	libjpeg-turbo8/trixie
	libpinyin-data/trixie
	libpinyin13/trixie
	libpoppler-cpp0v5/jammy
	libpoppler-qt5-1/jammy
	libpoppler126/jammy
	maliit-keyboard/jammy
	openresolv/trixie
	plasma-gamemode/trixie
	poppler-utils/jammy
	python3-pyqt5/jammy
	wireguard/trixie
	wireplumber/trixie
	libwireplumber-0.4-0/trixie
'

install $NX_DESKTOP_PKG $UNISON_DESKTOP_PKGS


rm \
	/etc/apt/sources.list.d/neon-user-repo.list \
	/etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	55751E5D \
	90E51522 > /dev/null

update
