#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list

update


#   Add Calamares.

CALAMARES_PKGS='
	efibootmgr
	calamares=3.2.62-0xneon+22.04+jammy+release+build15+nitrux
	calamares-qml-settings-nitrux
	dosfstools
	squashfs-tools
'

install $CALAMARES_PKGS


rm \
	/etc/apt/sources.list.d/neon-user-repo.list

remove_repo_keys \
	55751E5D > /dev/null

update
