#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#   Add Calamares.

CALAMARES_PKGS='
	efibootmgr
	calamares=3.2.62-0xneon+22.04+jammy+release+build15+nitrux
	calamares-qml-settings-nitrux
	dosfstools
	squashfs-tools
'

install $CALAMARES_PKGS
