#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


#	Install these packages first because now libappimageupdate and zsync2 provide files found in other packages.

ZSYNC_LIBAIU_PKGS='
	libappimageupdate
	zlib1g-dev
	zsync2
'

install_force_overwrite $ZSYNC_LIBAIU_PKGS

NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
	nx-desktop-appimages-vfio
	nx-desktop-apps-vfio
'

UNISON_DESKTOP_PKGS='
	fcitx5-frontend-qt6/jammy
	kde-config-fcitx5=5.0.11-1
	kgpg/jammy
	kwalletmanager/jammy
	libblockdev-crypto2=2.28-2
	libblockdev-utils2=2.28-2
	libjpeg-turbo8=2.1.5-2ubuntu1
	libmysqlclient21=8.0.34-1
	libpam-kwallet5/jammy
	libwireplumber-0.4-0=0.4.14-2
	openresolv=3.13.1-2
	plasma-firewall/jammy
	plasma-gamemode=0.0~git20220224.3adea2bd-2
	wireguard=1.0.20210914-1ubuntu3
	wireplumber=0.4.14-2
'

MISC_PKGS='

'

install $NX_DESKTOP_PKG $UNISON_DESKTOP_PKGS $MISC_PKGS

rm \
	/etc/apt/sources.list.d/neon-user-repo.list \
	/etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

update
