#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


#	Install these packages first because now libappimageupdate and zsync2 provide files found in other packages.

ZSYNC_LIBAIU_PKGS='
	libappimageupdate
	zlib1g-dev
	zsync2
'

install_force_overwrite $ZSYNC_LIBAIU_PKGS

NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
	nx-desktop-appimages-vfio
	nx-desktop-apps-vfio
'

UNISON_DESKTOP_PKGS='

'

MISC_PKGS='
	fcitx5-module-lua/trixie
	kde-config-flatpak/trixie
	kde-config-gtk-style/jammy
	kio-extras/jammy
	kwin-bismuth/trixie
	libjpeg-turbo8/trixie
'

install_downgrades $NX_DESKTOP_PKG $UNISON_DESKTOP_PKGS $MISC_PKGS

rm \
	/etc/apt/sources.list.d/neon-user-repo.list \
	/etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

update
