#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


add_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

cp /configs/files/sources/sources.list.neon.user /etc/apt/sources.list.d/neon-user-repo.list
cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


#	Install these packages first because now libappimageupdate and zsync2 provide files found in other packages.

ZSYNC_LIBAIU_PKGS='
	libappimageupdate
	zlib1g-dev
	zsync2
'

install_force_overwrite $ZSYNC_LIBAIU_PKGS

NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
	nx-desktop-appimages-vfio
	nx-desktop-apps-vfio
'

UNISON_DESKTOP_PKGS='

'

MISC_PKGS='
	nitrux-hardware-drivers-legacy
	gstreamer1.0-libav
	gstreamer1.0-plugins-good
	gstreamer1.0-pulseaudio
	phonon4qt5
	phonon4qt5-backend-vlc
	qt5-image-formats-plugins
	kde-config-flatpak/trixie
	kde-config-gtk-style/jammy
	kio-extras/jammy
	kwin-bismuth/sid
	plasma-desktop
	plasma-widgets-addons
	kaccounts-integration
	kio-gdrive
	nx-clock-applet
	nx-desktop-apps-legacy
	nx-notifications-applet
	nx-simplemenu-applet
	nx-systemtray-applet
	fcitx5-frontend-gtk2
	fcitx5-frontend-gtk3
	fcitx5-frontend-gtk4
	fcitx5-frontend-qt6
	fcitx5-modules/jammy
	fcitx5-module-lua
	fcitx5-mozc
	maliit-inputcontext-gtk2
	maliit-inputcontext-gtk3
	0install
	ghostscript-x
	gir1.2-gtk-3.0
	gnome-keyring
	graphviz
	gtk2-engines-murrine
	gtk3-engines-breeze
	open-vm-tools-desktop
	pulseaudio-module-bluetooth
	qt5-gtk-platformtheme
	rofi
	waydroid
	waydroid-openrc
	zenity
	libdbusmenu-gtk3-4
	libgtk2.0-0
	libnotify-bin
	plasma-workspace-wayland

'

install $NX_DESKTOP_PKG $UNISON_DESKTOP_PKGS $MISC_PKGS

rm \
	/etc/apt/sources.list.d/neon-user-repo.list \
	/etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	55751E5D \
	90E51522 \
	1DCEE19C > /dev/null

update
