#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#   Upgrade the MESA packages.

cp /configs/files/sources/sources.list.debian.experimental /etc/apt/sources.list.d/debian-experimental-repo.list

update

MESA_LIBS_PKGS='
    libegl-mesa0/experimental
    libgbm1/experimental
    libgl1-mesa-dri/experimental
    libglapi-mesa/experimental
    libglx-mesa0/experimental
    libxatracker2/experimental
    mesa-va-drivers/experimental
    mesa-vdpau-drivers/experimental
    mesa-vulkan-drivers/experimental
'

only_upgrade $MESA_LIBS_PKGS

rm \
	/etc/apt/sources.list.d/debian-experimental-repo.list

update
