#!/usr/bin/env bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


echo "Skip this step; MESA from Git is broken"

# add_repo_keys \
# 	A03A4626 > /dev/null

# cp /configs/files/sources/sources.list.mesa.git.ppa /etc/apt/sources.list.d/mesa-git-ppa.list

# update

# MESA_LIBS_PKGS='
# 	libdrm-amdgpu1
# 	libdrm-common
# 	libdrm-intel1
# 	libdrm-nouveau2
# 	libdrm-radeon1
# 	libdrm2
# 	libegl-mesa0
# 	libgbm1
# 	libgl1-mesa-dri
# 	libglapi-mesa
# 	libglx-mesa0
# 	libxatracker2
# 	mesa-va-drivers
# 	mesa-vdpau-drivers
# 	mesa-vulkan-drivers
# '

# only_upgrade_force_overwrite $MESA_LIBS_PKGS

# rm \
# 	/etc/apt/sources.list.d/mesa-git-ppa.list

# remove_repo_keys \
# 	A03A4626 > /dev/null

# update
