#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


#	Check currently installed services.

ls -lh \
	/etc/runlevels/{boot,default,nonetwork,off,recovery,shutdown,sysinit} \
	/etc/init.d


#	Add OpenRC configuration.
#
#	Due to how the upstream openrc package "works," we need to put this package at the end of the build process.
#	Otherwise, we end up with an unbootable system.
#
#	See https://github.com/Nitrux/openrc-config/issues/1

OPENRC_CONFIG='
	openrc-config
'

install $OPENRC_CONFIG


#	Add hook scripts for initram generation.

cp /configs/files/initramfs/crypttab-initramfs-hook /usr/share/initramfs-tools/hooks/
cp /configs/files/initramfs/vfio-initramfs-hook /usr/share/initramfs-tools/hooks/


#   Overwrite 15autologin to enable autologin for Plasma Wayland in casper for Live session.

cat /configs/scripts/others/casper/15autologin > /usr/share/initramfs-tools/scripts/casper-bottom/15autologin


#	Add modules to initramfs.

printf '%s\n' hv_vmbus hv_storvsc hv_blkvsc hv_netvsc exfat >> /etc/initramfs-tools/modules


#	Add modules to load at boot time.

printf '%s\n' fuse nvidia nvidia_drm nvidia_modeset amdgpu i915 exfat loop >> /etc/modules


update-initramfs -c -k all
