#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Remove build sources.
#    -- Comment the command(s) to debug packages in a Live session.

find /etc/apt/sources.list.d/ -type f \( -name "*.list" -o -name "*.sources" \) -delete


# -- Remove leftover packages.

autoremove


# -- Move APT and dpkg out of the way.
#    -- Comment the command(s) to debug packages in a Live session.

for entry in \
"bin apt 1" \
"bin apt-cache 2" \
"bin apt-cdrom 3" \
"bin apt-config 4" \
"bin apt-get 5" \
"bin apt-mark 6" \
"bin dpkg 7" \
"bin dpkg-deb 8" \
"bin dpkg-divert 9" \
"bin dpkg-maintscript-helper 10" \
"bin dpkg-query 11" \
"bin dpkg-realpath 12" \
"bin dpkg-split 13" \
"bin dpkg-statoverride 14" \
"bin dpkg-trigger 15" \
"bin dpkg-architecture 16" \
"bin dpkg-buildapi 17" \
"bin dpkg-buildflags 18" \
"bin dpkg-buildpackage 19" \
"bin dpkg-buildtree 20" \
"bin dpkg-checkbuilddeps 21" \
"bin dpkg-distaddfile 22" \
"bin dpkg-genbuildinfo 23" \
"bin dpkg-genchanges 24" \
"bin dpkg-gencontrol 25" \
"bin dpkg-gensymbols 26" \
"bin dpkg-mergechangelogs 27" \
"bin dpkg-name 28" \
"bin dpkg-parsechangelog 29" \
"bin dpkg-scanpackages 30" \
"bin dpkg-scansources 31" \
"bin dpkg-shlibdeps 32" \
"bin dpkg-source 33" \
"bin dpkg-vendor 34" \
"sbin dpkg-preconfigure 35" \
"sbin dpkg-reconfigure 36"
do
    set -- "$entry"
    dir="$1"
    name="$2"
    idx="$3"
    if [ -e "/usr/$dir/$name" ]; then
        mv "/usr/$dir/$name" "/opt/$idx"
    fi
done

for n in $(seq 1 36); do chmod -x "/opt/$n"; done

chmod -x /var/lib/dpkg


# -- Add install scripts here.
#    -- Use undebianize from Calamares to delete these files from the root.
#    -- Comment the command(s) to debug packages in a Live session.

DEST_DIR="/usr/bin"
LINKER_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/linker"
UNDEBIANIZE_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/undebianize"

wget -P "$DEST_DIR" "$LINKER_URL"
wget -P "$DEST_DIR" "$UNDEBIANIZE_URL"

chmod +x "$DEST_DIR/linker"
chmod +x "$DEST_DIR/undebianize"


# -- Display dialog to notify users of software management policy.
#    -- Comment the command(s) to debug packages in a Live session.

for n in apt apt-cache apt-cdrom apt-config apt-get apt-mark; do
    ln -sf /usr/local/bin/nx-pkgmgr-policy "/usr/bin/$n"
done

for n in \
    dpkg dpkg-deb dpkg-divert dpkg-maintscript-helper dpkg-query dpkg-realpath \
    dpkg-split dpkg-statoverride dpkg-trigger \
    dpkg-architecture dpkg-buildapi dpkg-buildflags dpkg-buildpackage \
    dpkg-buildtree dpkg-checkbuilddeps dpkg-distaddfile \
    dpkg-genbuildinfo dpkg-genchanges dpkg-gencontrol dpkg-gensymbols \
    dpkg-mergechangelogs dpkg-name dpkg-parsechangelog \
    dpkg-scanpackages dpkg-scansources dpkg-shlibdeps dpkg-source dpkg-vendor
do
    ln -sf /usr/local/bin/nx-pkgmgr-policy "/usr/bin/$n"
done

for n in dpkg-preconfigure dpkg-reconfigure; do
    ln -sf /usr/local/bin/nx-pkgmgr-policy "/usr/sbin/$n"
done
