#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Remove build sources.
#    -- Comment the command(s) to debug packages in a Live session.

find /etc/apt/sources.list.d/ -type f \( -name "*.list" -o -name "*.sources" \) -delete


# -- Remove leftover packages.

autoremove


# -- Move apt, apt-*, dpkg, and dpkg-* out of the way.
#    -- Comment the command(s) to debug packages in a Live session.

while read -r name idx; do
    src="/usr/bin/$name"
    [ -e "$src" ] || continue
    mv "$src" "/opt/$idx"
done <<'EOF'
apt 1
apt-cache 2
apt-cdrom 3
apt-config 4
apt-get 5
apt-mark 6
dpkg 7
dpkg-deb 8
dpkg-divert 9
dpkg-maintscript-helper 10
dpkg-query 11
dpkg-realpath 12
dpkg-split 13
dpkg-statoverride 14
dpkg-trigger 15
dpkg-architecture 16
dpkg-buildapi 17
dpkg-buildflags 18
dpkg-buildpackage 19
dpkg-buildtree 20
dpkg-checkbuilddeps 21
dpkg-distaddfile 22
dpkg-genbuildinfo 23
dpkg-genchanges 24
dpkg-gencontrol 25
dpkg-gensymbols 26
dpkg-mergechangelogs 27
dpkg-name 28
dpkg-parsechangelog 29
dpkg-scanpackages 30
dpkg-scansources 31
dpkg-shlibdeps 32
dpkg-source 33
dpkg-vendor 34
dpkg-preconfigure 35
dpkg-reconfigure 36
EOF

chmod -x /opt/{1..36}
chmod -x /var/lib/dpkg


# -- Add install scripts here.
#    -- Use undebianize from Calamares to delete these files from the root.
#    -- Comment the command(s) to debug packages in a Live session.

DEST_DIR="/usr/bin"
LINKER_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/linker"
UNDEBIANIZE_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/undebianize"

wget -P "$DEST_DIR" "$LINKER_URL"
wget -P "$DEST_DIR" "$UNDEBIANIZE_URL"

chmod +x "$DEST_DIR/linker"
chmod +x "$DEST_DIR/undebianize"


# -- Display dialog to notify users of software management policy.

ln -sf /usr/local/bin/nx-pkgmgr-policy /usr/bin/apt
ln -sf /usr/local/bin/nx-pkgmgr-policy /usr/bin/{apt-cache,apt-cdrom,apt-config,apt-get,apt-mark}
ln -sf /usr/local/bin/nx-pkgmgr-policy /usr/bin/{dpkg,dpkg-deb,dpkg-divert,dpkg-mainscript-helper,dpkg-query,dpkg-realpath,dpkg-split,spkg-statoverride,dpkg-trigger}
