#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu


# -- Edit 15autologin to enable autologin in casper for the Live session.

# shellcheck disable=SC2034
SDDM_DESKTOP_SESSION="blackbox.desktop"
REPLACE_CASPER_AUTOLOGIN_SCRIPT="/usr/share/initramfs-tools/scripts/casper-bottom/15autologin"

mkdir -p "$(dirname "$REPLACE_CASPER_AUTOLOGIN_SCRIPT")"

cat > "$REPLACE_CASPER_AUTOLOGIN_SCRIPT" << EOF_AUTOLOGIN_SCRIPT_QUOTED
#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
prereqs)
       prereqs
       exit 0
       ;;
esac

# shellcheck source=/dev/null
. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -f /root/usr/bin/sddm ]; then
    SDDM_SESSION_PLACEHOLDER
    
    if ! [ -f "/root/usr/share/xsessions/\$sddm_session" ] && \\
       ! [ -f "/root/usr/share/wayland-sessions/\$sddm_session" ]; then
        log_warning_msg "SDDM session file \$sddm_session not found in /root/usr/share/xsessions/ or /root/usr/share/wayland-sessions/. Autologin might fail."
    fi

    AUTOLOGIN_CONF="/root/etc/sddm.conf.d/live_autologin.conf"
    mkdir -p "\$(dirname "\$AUTOLOGIN_CONF")"
    
    cat >"\$AUTOLOGIN_CONF" << EOF_SDDM_CONF_INNER
[Autologin]
User=\$USERNAME
Session=\$sddm_session
EOF_SDDM_CONF_INNER

    log_end_msg "SDDM autologin configured for user \$USERNAME with session \$sddm_session in \$AUTOLOGIN_CONF"

else
    log_end_msg "SDDM not found at /root/usr/bin/sddm. Skipping SDDM autologin setup."
fi

log_end_msg
EOF_AUTOLOGIN_SCRIPT_QUOTED

sed -i "s|SDDM_SESSION_PLACEHOLDER|sddm_session=\"\${SDDM_DESKTOP_SESSION}\"|" "$REPLACE_CASPER_AUTOLOGIN_SCRIPT"


# -- Always update initramfs after adding, removing or editing hook scripts.

update-initramfs -u -k all