#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source useful functions.
# shellcheck source=/dev/null

source /configs/scripts/others/misc-funcs


# -- Remove these lines from /usr/share/initramfs-tools/scripts/casper because they're relevant in Ubuntu but not here.

sed -i '/touch \/root\/var\/crash\/crash.init/d; /rm \/root\/var\/crash\/crash.init/d' /usr/share/initramfs-tools/scripts/casper


# -- Check if the root account is disabled, if not, disable it by locking it.

if [[ $(passwd -S root | awk '{print $2}') == "L" ]]; then
   echo "Root account is already disabled"
else
   passwd -l root
   echo "Root account has been disabled"
fi


# -- Edit console-setup to match the user settings.

update_console_settings ACTIVE_CONSOLES '/dev/tty[1-6]'
update_console_settings CHARMAP 'UTF-8'
update_console_settings VIDEOMODE ''
update_console_settings CODESET 'Uni2'
update_console_settings FONTFACE 'Terminus'
update_console_settings FONTSIZE '16'


# -- Ensure Hyprland session is launched with D-Bus (OpenRC) from the greeter when using greetd.
#    -- See: https://wiki.gentoo.org/wiki/Greetd#Hyprland_session_with_D-Bus_.28OpenRC.29

DESKTOP_FILE="/usr/share/wayland-sessions/hyprland.desktop"

if [ -f "$DESKTOP_FILE" ] && ! grep -q "Exec=greetd-hyprland" "$DESKTOP_FILE"; then
    sed -i 's|^Exec=Hyprland|Exec=greetd-hyprland|' "$DESKTOP_FILE"
fi


# -- Create directory for elogind sleep hooks and add elogind sleep hook scripts.

mkdir -p /etc/elogind/system-sleep/

cp /configs/files/elogind_files/system-sleep/* /etc/elogind/system-sleep/


# -- Disable DrKonqi as we do not include debug symbols and it's useless otherwise.

chmod a-x /usr/lib/x86_64-linux-gnu/libexec/drkonqi 


# -- Disable plasmashell, kwin and the Plasma sessions.

chmod a-x /usr/bin/{plasmashell,kwin_wayland}

rm -f /usr/share/xsessions/plasmax11.desktop
rm -f /usr/share/wayland-sessions/plasma.desktop


# -- Disable the KCMs that we don't use.

DELETE_UNUSED_KCMS_LAUNCHERS=(
    kcm_autostart.desktop
    kcm_breezedecoration.desktop
    kcm_desktoptheme.desktop
    kcm_feedback.desktop
    kcm_fontinst.desktop
    kcm_kwin_effects.desktop
    kcm_kwin_scripts.desktop
    kcm_kwin_virtualdesktops.desktop
    kcm_kwindecoration.desktop
    kcm_kwinoptions.desktop
    kcm_kwinrules.desktop
    kcm_kwintabbox.desktop
    kcm_kwinxwayland.desktop
    kcm_lookandfeel.desktop
    kcm_netpref.desktop
    kcm_nightlight.desktop
    kcm_notifications.desktop
    kcm_proxy.desktop
    kcm_regionandlang.desktop
    kcm_trash.desktop
    kcm_virtualkeyboard.desktop
    kcm_wallpaper.desktop
    kcm_webshortcuts.desktop
)

DELETE_UNUSED_KCMS_LIBEXEC=(
    kcm_autostart.so
    kcm_breezedecoration.so
    kcm_desktoptheme.so
    kcm_feedback.so
    kcm_fontinst.so
    kcm_kwin_effects.so
    kcm_kwin_scripts.so
    kcm_kwin_virtualdesktops.so
    kcm_kwindecoration.so
    kcm_kwinoptions.so
    kcm_kwinrules.so
    kcm_kwintabbox.so
    kcm_kwinxwayland.so
    kcm_lookandfeel.so
    kcm_netpref.so
    kcm_nightlight.so
    kcm_notifications.so
    kcm_proxy.so
    kcm_regionandlang.so
    kcm_trash.so
    kcm_virtualkeyboard.so
    kcm_wallpaper.so
    kcm_webshortcuts.so
)


DELETE_UNUSED_KCMS_QWIDGETS_LIBEXEC=(
    kcm_kwinoptions.so
    kcm_kwinscreenedges.so
    kcm_kwintabbox.so
    kcm_kwintouchscreen.so
    kwincompositing.so
)


DELETE_UNUSED_SYSTEMSETTINGS_CATEGORIES=(
    settings-applications-permissions.desktop
    settings-hardware-display.desktop
    settings-hardware-input-pointing-devices.desktop
    settings-hardware-input-touchscreen.desktop
    settings-hardware-keyboard.desktop
    settings-personalization.desktop
    settings-workspace-search.desktop
    settings-workspace-session.desktop
    settings-workspace-windowmanagement.desktop
    settings-workspace.desktop
    settings-hardware-removable-storage.desktop
)

rm -f  \
    "${DELETE_UNUSED_KCMS_LAUNCHERS[@]/#//usr/share/applications/}" \
    "${DELETE_UNUSED_KCMS_LIBEXEC[@]/#//usr/lib/x86_64-linux-gnu/qt6/plugins/plasma/kcms/systemsettings/}" \
    "${DELETE_UNUSED_KCMS_QWIDGETS_LIBEXEC[@]/#//usr/lib/x86_64-linux-gnu/qt6/plugins/plasma/kcms/systemsettings_qwidgets/}" \
    "${DELETE_UNUSED_SYSTEMSETTINGS_CATEGORIES[@]/#//usr/share/systemsettings/categories/}"


# -- Remove CLI utilities launchers.
#    -- Why the hell do CLI utilities have a god damn desktop launcher to begin with?!

DELETE_CLI_UTILS_LAUNCHERS=(
    htop.desktop
    lstopo.desktop
    micro.desktop
)

rm -f  \
    "${DELETE_CLI_UTILS_LAUNCHERS[@]/#//usr/share/applications/}" \


# -- Set QtGreet theme.

QTGREET_CONFIG="/etc/qtgreet/config.ini"

if [ -f "$QTGREET_CONFIG" ] && grep -q "Theme = default" "$QTGREET_CONFIG"; then
    sed -i 's|^Theme = default|Theme = nitrux|' "$QTGREET_CONFIG"
fi


# -- Create directories for aesthethic FHS.

BASE_DIR="/System"

declare -a DIRS=(
    "${BASE_DIR}/Boot"
    "${BASE_DIR}/Binaries/Administrative"
    "${BASE_DIR}/Binaries/Standard"
    "${BASE_DIR}/Binaries/Optional"
    "${BASE_DIR}/Configuration"
    "${BASE_DIR}/Devices"
    "${BASE_DIR}/Filesystems/External"
    "${BASE_DIR}/Filesystems/Internal"
    "${BASE_DIR}/Libraries"
    "${BASE_DIR}/Shareable"
    "${BASE_DIR}/Variable"
    "/Users"
)

for dir in "${DIRS[@]}"; do
    echo "Creating directory: $dir"
    mkdir -p "$dir" || echo "Failed to create $dir"
done


# -- Hide original FHS directories.

cp /configs/files/other/hidden /.hidden


# -- Create /Applications directory.

mkdir -p /Applications


# -- Mitigate Bluetooth devices disconnecting randomly.

MAIN_CONF="/etc/bluetooth/main.conf"
INPUT_CONF="/etc/bluetooth/input.conf"

if [ -f "$MAIN_CONF" ]; then
    sed -i \
        -e 's/^#DiscoverableTimeout = 0/DiscoverableTimeout = 0/' \
        -e 's/^#PairableTimeout = 0/PairableTimeout = 0/' \
        -e 's/^#ControllerMode = dual/ControllerMode = bredr/' \
        -e 's/^#AutoEnable=true/AutoEnable=true/' \
        "$MAIN_CONF"
fi

if [ -f "$INPUT_CONF" ]; then
    sed -i 's/^#IdleTimeout=0/IdleTimeout=0/' "$INPUT_CONF"
fi


# -- Grab the latest clipvault release and drop it to a directory in PATH.

arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) target="x86_64-unknown-linux-gnu" ;;
  aarch64|arm64) target="aarch64-unknown-linux-gnu" ;;
  *) echo "unsupported architecture: $arch"; exit 1 ;;
esac

tag="${CLIPVAULT_TAG:-latest}"
asset="clipvault-${target}.tar.gz"
base="https://github.com/Rolv-Apneseth/clipvault/releases"
url="$base/latest/download/$asset"
[ "$tag" = "latest" ] || url="$base/download/$tag/$asset"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$url" -o "$tmp/$asset"
else
  wget -qO "$tmp/$asset" "$url"
fi

tar -C "$tmp" -xf "$tmp/$asset"

binpath="$(find "$tmp" -type f -name clipvault -perm -u+x | head -n1)"
[ -n "$binpath" ] || { echo "clipvault binary not found in archive"; exit 1; }

install -m 0755 "$binpath" /usr/bin/clipvault


# -- Install NX AppHub and NX AppHub Daemon to a system-wide venv.

pipx install --global git+https://github.com/Nitrux/nx-apphub.git
pipx install --global git+https://github.com/Nitrux/nx-apphubd.git


# -- Replace user-setup-apply so that it shuts up about dpkg.

mkdir -p /usr/lib/user-setup/

cp /configs/files/other/user-setup-apply /usr/lib/user-setup/user-setup-apply


# -- Replace update-grub with our version that doesn't break *OUR* distribution.

cp /configs/files/grub_files/update-grub /usr/sbin/update-grub


# -- Replace /usr/lib/grub/grub-sort-version with a version that doesn't use apt.pkg so it can generate a usable boot menu.

cp /configs/files/grub_files/grub-sort-version /usr/lib/grub/grub-sort-version


# -- Add user for OpenRazer (which is missing for some reason!).

# if id -u razer >/dev/null 2>&1; then
#     echo "User razer already exists."
# else
#     useradd -r -s /bin/false -M razer
#     echo "User razer created successfully."
# fi

# usermod -L razer


# -- Add user for AIDE (which is missing for some reason!).


# if id -u _aide >/dev/null 2>&1; then
#     echo "User _aide already exists."
# else
#     useradd -r -s /bin/false -M _aide
#     echo "User _aide created successfully."
# fi

# usermod -L _aide


# -- Replace aide.conf and 10_aide_hostname.

# cp /configs/files/conf/aide.conf /etc/aide/aide.conf
# cp /configs/files/other/10_aide_hostname /etc/aide/aide.conf.d/10_aide_hostname


# -- Replace dnscrypt-proxy default configuration.

# cat /configs/files/other/dnscrypt-proxy-settings/dnscrypt-proxy.toml > /etc/dnscrypt-proxy/dnscrypt-proxy.toml

# cp /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md /var/cache/dnscrypt-proxy/public-resolvers.md
# cp /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md.minisig /var/cache/dnscrypt-proxy/public-resolvers.md.minisig


# -- Add variable to PAM for Firefox to work with touchscreens in Wayland.

# sed -i "$ a \  " /etc/security/pam_env.conf
# sed -i "$ a #  Make Firefox work with touchscreens in Wayland" /etc/security/pam_env.conf
# sed -i "$ a MOZ_ENABLE_WAYLAND DEFAULT=0 OVERRIDE=1" /etc/security/pam_env.conf


# -- Fix issue with AppArmor profile for Samba that is too restrictive.

# APPARMOR_PROFILE="/etc/apparmor.d/usr.sbin.smbd"

# sed -i '/capability setuid,/a\  capability sys_ptrace,' "$APPARMOR_PROFILE"
# sed -i 's|@{HOMEDIRS}/\*\* .*|@{HOMEDIRS}/** rwk,|' "$APPARMOR_PROFILE"


# -- Disable the virtualization extensions (like Intel VT-x or AMD-V) from loading automatically when the KVM module is loaded into the kernel.
#   -- NOTE: This is to make VirtualBox work.

# sed -i "/^options kvm /a options kvm enable_virt_at_load=0" /etc/modprobe.d/kvm.conf


# -- Enforce sync only for specific filesystems, like vfat.

sed -i '/^\[defaults\]/a\vfat_defaults=sync' /etc/udisks2/udisks2.conf


# -- Add nvidia_oc binary to overclock NVIDIA GPUs on Wayland.

FILE_URL="https://github.com/Dreaming-Codes/nvidia_oc/releases/download/0.1.11/nvidia_oc"
DEST_DIR="/usr/bin"
DEST_FILE="$DEST_DIR/nvidia-oc"
if curl -L -o "$DEST_FILE" "$FILE_URL"; then
    chmod +x "$DEST_FILE"
else
    exit 1
fi


# -- Disable AppArmor profile for bubblewrap that breaks Flatpak, see https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811

ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable/


# -- Link the existing AppArmor profile for Firejail so it actually works.

mv /etc/apparmor.d/firejail-default /etc/apparmor.d/usr.bin.firejail


# -- Create directory for os-prober.

mkdir -p /var/lib/os-prober/mount


# -- Change path where NetworkManager saves wireless connections.

echo -e "\n[keyfile]\npath=/var/lib/NetworkManager" | tee -a /etc/NetworkManager/NetworkManager.conf


# -- Replace this line in mkinitramfs so it shuts up about dpkg.

sed -i "s+DPKG_ARCH=\$(dpkg --print-architecture)+DPKG_ARCH=\$(uname -m | sed \"s/x86_64/amd64/\")+g" /usr/sbin/mkinitramfs


# -- Enable ufw by default.

ufw enable


# -- Remove unwanted kernel and initrd links from /boot and /.

rm -f /boot/{vmlinuz,initrd.img,vmlinuz.old,initrd.img.old} \
      /{vmlinuz.old,initrd.img.old} 2>/dev/null || true


# -- Ensure the links in / point to the files in /boot.

boot_dir="/boot"
vmlinuz_pattern="vmlinuz-*liquorix-*"
initrd_pattern="initrd.img-*liquorix-*"

vmlinuz_file=$(find "$boot_dir" -maxdepth 1 -type f -name "$vmlinuz_pattern" | head -1)
initrd_file=$(find "$boot_dir" -maxdepth 1 -type f -name "$initrd_pattern" | head -1)

if [ -n "$vmlinuz_file" ]; then
    echo "Creating/updating symlink for /vmlinuz"
    create_symlink "$vmlinuz_file" "/vmlinuz"
else
    echo "Error: No matching vmlinuz file found in $boot_dir."
fi

if [ -n "$initrd_file" ]; then
    echo "Creating/updating symlink for /initrd.img"
    create_symlink "$initrd_file" "/initrd.img"
else
    echo "Error: No matching initrd.img file found in $boot_dir."
fi


# -- Create necessary directories to put files for kboot and create soft links for liquorix kernel files.

mkdir -p /kboot/{debian,mainline,liquorix}

for file in /boot/vmlinuz-*liquorix-amd64; do
    create_symlink "$file" "/kboot/liquorix/vmlinuz"
done

for file in /boot/initrd.img-*liquorix-amd64; do
    create_symlink "$file" "/kboot/liquorix/initrd.img"
done


# -- Remove rootfs leftovers

rm -f /var/log/bootstrap.log


# -- Add modules to load at boot time.

printf '%s\n' amdgpu i915 fuse exfat loop  >> /etc/modules-load.d/load-modules-at-boot.conf


# -- Remove KWallet Manager desktop launcher since the intention is to use the KCM.

rm -f /usr/share/applications/org.kde.kwalletmanager.desktop
