#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu


# -- Function to create symlinks.

create_symlink() {
    local source="$1"
    local destination="$2"

    ln -svf "$source" "$destination"
}


# -- Add other modules to load at boot time.

printf '%s\n' fuse exfat loop >> /etc/modules-load.d/additional-modules-boot-time.conf


# -- Remove unwanted kernel and initrd links from /boot and /.

rm -f /boot/{vmlinuz,initrd.img,vmlinuz.old,initrd.img.old} \
      /{vmlinuz.old,initrd.img.old} 2>/dev/null || true


# -- Create symlinks for MauiKit 4 and MauiKit Frameworks 4.

MAUIKIT_VERSION="4.0.2"
MAUIKIT_SO_VERSION="4"

create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKit$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKit$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiMan$MAUIKIT_SO_VERSION.so.$MAUIKIT_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiMan$MAUIKIT_SO_VERSION.so$MAUIKIT_SO_VERSION"


# -- Create symlinks for Mauikit 3 because Calamares uses it.

# MAUIKIT3_VERSION="3.1.0"

# create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/controls/libMauiKit3.so.$MAUIKIT3_VERSION" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/controls/libMauiKit3.so"
# create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKit3.so.$MAUIKIT3_VERSION" "/usr/lib/x86_64-linux-gnu/libMauiKit3.so"


# -- Move APT and dpkg out of the way.
# -- Use undebianize to delete these files from the root.

mv /usr/bin/apt /opt/1
mv /usr/bin/apt-get /opt/2
mv /usr/bin/dpkg /opt/3

chmod -x /opt/{1,2,3}


# -- Enable ufw by default.
# -- Add rules for ports so Waydroid to access the Internet.
# -- Add rules for KDE Connect.

ufw enable
ufw allow 53
ufw allow 67
ufw default allow FORWARD
ufw allow 1714:1764/udp
ufw allow 1714:1764/tcp


# -- Check if the root account is disabled, if not, disable it by locking it.

if [[ $(passwd -S root | awk '{print $2}') == "L" ]]; then
   echo "Root account is already disabled"
else
   passwd -l root
   echo "Root account has been disabled"
fi


# -- Replace /usr/lib/grub/grub-sort-version with a version that doesn't use apt.pkg so it can generate a usable boot menu.

$(which cp) /configs/files/grub_files/grub-sort-version /usr/lib/grub/grub-sort-version


# -- Create directories for aesthethic FHS.

BASE_DIR="/System"

declare -a DIRS=(
    "${BASE_DIR}/Boot"
    "${BASE_DIR}/Binaries/Administrative"
    "${BASE_DIR}/Binaries/Standard"
    "${BASE_DIR}/Binaries/Optional"
    "${BASE_DIR}/Configuration"
    "${BASE_DIR}/Devices"
    "${BASE_DIR}/Filesystems/External"
    "${BASE_DIR}/Filesystems/Internal"
    "${BASE_DIR}/Libraries"
    "${BASE_DIR}/Shareable"
    "${BASE_DIR}/Variable"
    "/Users"
)

for dir in "${DIRS[@]}"; do
    echo "Creating directory: $dir"
    mkdir -p "$dir" || echo "Failed to create $dir"
done


# -- Hide original FHS directories.

$(which cp) /configs/files/other/hidden /.hidden


# -- Replace update-grub with our version that doesn't break Nitrux.

$(which cp) /configs/scripts/others/update-grub /usr/sbin/update-grub


# -- Replace this line in mkinitramfs so it shuts up about dpkg.

sed -i "s+DPKG_ARCH=\$(dpkg --print-architecture)+DPKG_ARCH=\$(uname -m | sed \"s/x86_64/amd64/\")+g" /usr/sbin/mkinitramfs


# -- Replace user-setup-apply so that it shuts up about dpkg.

$(which cp) /configs/scripts/others/user-setup-apply /usr/lib/user-setup/user-setup-apply


# -- Change path where NetworkManager saves wireless connections.

echo -e "\n[keyfile]\npath=/var/lib/NetworkManager" | tee -a /etc/NetworkManager/NetworkManager.conf


# -- Create directory for os-prober.

mkdir -p /var/lib/os-prober/mount


# -- Edit NVIDIA X Settings launcher.

# sed -i '/^Categories=/ s/\bSystem;//' /usr/share/applications/nvidia-settings.desktop


# -- Edit CoreCtrl launcher.

sed -i '/^Categories=/ s/\bSystem;//; s/\bSettings;//' /usr/share/applications/org.corectrl.CoreCtrl.desktop


# -- Disable AppArmor profile for bubblewrap that breaks Flatpak, see https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2072811

ln -s /etc/apparmor.d/bwrap-userns-restrict /etc/apparmor.d/disable/


# -- Add nvidia_oc binary to overclock NVIDIA GPUs on Wayland.

NV_OC_FILE_URL="https://github.com/Dreaming-Codes/nvidia_oc/releases/download/0.1.11/nvidia_oc"
NV_OC_DEST_DIR="/usr/bin"
NV_OC_DEST_FILE="$NV_OC_DEST_DIR/nvidia-oc"
if curl -L -o "$NV_OC_DEST_FILE" "$NV_OC_FILE_URL"; then
    chmod +x "$NV_OC_DEST_FILE"
else
    exit 1
fi


# -- Add undebianize and linker scripts.

SCRIPTS_DEST_DIR="/usr/bin"
LINKER_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/linker"
UNDEBIANIZE_URL="https://raw.githubusercontent.com/Nitrux/storage/master/Scripts/undebianize"

wget -P "$SCRIPTS_DEST_DIR" "$LINKER_URL"
wget -P "$SCRIPTS_DEST_DIR" "$UNDEBIANIZE_URL"

chmod +x "$SCRIPTS_DEST_DIR/linker"
chmod +x "$SCRIPTS_DEST_DIR/undebianize"


# -- Enforce sync for specific filesystems, like vfat.

sed -i '/^\[defaults\]/a\vfat_defaults=sync' /etc/udisks2/udisks2.conf


# -- Disable the virtualization extensions (like Intel VT-x or AMD-V) from loading automatically when the KVM module is loaded into the kernel.
# -- INFO: This is to make VirtualBox work.

touch /etc/modprobe.d/kvm.conf
sed -i "/^options kvm /a options kvm enable_virt_at_load=0" /etc/modprobe.d/kvm.conf


# -- Mitigate Bluetooth devices disconnecting randomly.

MAIN_CONF="/etc/bluetooth/main.conf"
INPUT_CONF="/etc/bluetooth/input.conf"

if [ -f "$MAIN_CONF" ]; then
    sed -i \
        -e 's/^#DiscoverableTimeout = 0/DiscoverableTimeout = 0/' \
        -e 's/^#PairableTimeout = 0/PairableTimeout = 0/' \
        -e 's/^#ControllerMode = dual/ControllerMode = bredr/' \
        "$MAIN_CONF"
fi

if [ -f "$INPUT_CONF" ]; then
    sed -i 's/^#IdleTimeout=0/IdleTimeout=0/' "$INPUT_CONF"
fi


# -- Fix issue with AppArmor profile for Samba that is too restrictive.

APPARMOR_PROFILE="/etc/apparmor.d/usr.sbin.smbd"

sed -i '/capability setuid,/a\  capability sys_ptrace,' "$APPARMOR_PROFILE"
sed -i 's|@{HOMEDIRS}/\*\* .*|@{HOMEDIRS}/** rwk,|' "$APPARMOR_PROFILE"


# -- Edit Shelf launcher.

sed -i '/^Categories=/ s/\bGraphics;//' /usr/share/applications/org.kde.shelf.desktop


# -- Create directory for elogind sleep hooks and add elogind sleep hook scripts.

mkdir -p /etc/elogind/system-sleep/
$(which cp) /configs/files/other/elogind/system-sleep/* /etc/elogind/system-sleep/


# -- Edit Pix launcher.

sed -i '/^MimeType=/ s/inode\/directory;//' /usr/share/applications/org.kde.pix.desktop


# -- Rename the existing AppArmor profile for Firejail so it actually is used.

mv /etc/apparmor.d/firejail-default /etc/apparmor.d/usr.bin.firejail


# -- Add ghostty.

GTTY_URL_DEST_DIR="/usr/bin"
GTTY_URL="https://github.com/pkgforge-dev/ghostty-appimage/releases/download/v1.1.3%2B3/Ghostty-1.1.3-x86_64.AppImage"

wget -P -q "$GTTY_URL_DEST_DIR" "$GTTY_URL"
mv $GTTY_URL_DEST_DIR/Ghostty-1.1.3-x86_64.AppImage $GTTY_URL_DEST_DIR/ghostty
chmod +x "$GTTY_URL_DEST_DIR/ghostty"


# -- Hyprland session with D-Bus (OpenRC), according to Gentoo: https://wiki.gentoo.org/wiki/Greetd#Hyprland_session_with_D-Bus_.28OpenRC.29

DESKTOP_FILE="/usr/share/wayland-sessions/hyprland.desktop"

if [ -f "$DESKTOP_FILE" ] && ! grep -q "Exec=dbus-run-session Hyprland" "$DESKTOP_FILE"; then
    sed -i 's|^Exec=Hyprland|Exec=dbus-run-session Hyprland|' "$DESKTOP_FILE"
fi
