#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source useful functions.
# shellcheck source=/dev/null

source /configs/scripts/others/misc-funcs


# -- Remove these lines from /usr/share/initramfs-tools/scripts/casper because they're relevant in Ubuntu but not here.

sed -i '/touch \/root\/var\/crash\/crash.init/d; /rm \/root\/var\/crash\/crash.init/d' /usr/share/initramfs-tools/scripts/casper


# -- Check if the root account is disabled, if not, disable it by locking it.

if [[ $(passwd -S root | awk '{print $2}') == "L" ]]; then
   echo "Root account is already disabled"
else
   passwd -l root
   echo "Root account has been disabled"
fi


# -- Edit console-setup to match the user settings.

update_console_settings ACTIVE_CONSOLES '/dev/tty[1-6]'
update_console_settings CHARMAP 'UTF-8'
update_console_settings VIDEOMODE ''
update_console_settings CODESET 'Uni2'
update_console_settings FONTFACE 'Terminus'
update_console_settings FONTSIZE '16'


# -- Add motd.

cat /configs/files/other/motd > /etc/motd


# -- Ensure Hyprland session is launched with D-Bus (OpenRC) from the greeter when using greetd.
# -- See: https://wiki.gentoo.org/wiki/Greetd#Hyprland_session_with_D-Bus_.28OpenRC.29

DESKTOP_FILE="/usr/share/wayland-sessions/hyprland.desktop"

if [ -f "$DESKTOP_FILE" ] && ! grep -q "Exec=greetd-hyprland" "$DESKTOP_FILE"; then
    sed -i 's|^Exec=Hyprland|Exec=greetd-hyprland|' "$DESKTOP_FILE"
fi


# -- Create directory for elogind sleep hooks and add elogind sleep hook scripts.

mkdir -p /etc/elogind/system-sleep/

cp /configs/files/elogind_files/system-sleep/* /etc/elogind/system-sleep/


# -- Disable DrKonqi as we do not include debug symbols and it's useless otherwise.

chmod a-x /usr/lib/x86_64-linux-gnu/libexec/drkonqi 


# -- Disable plasmashell, kwin and the Plasma sessions.

chmod a-x /usr/bin/{plasmashell,kwin_wayland}

rm -f /usr/share/xsessions/plasmax11.desktop
rm -f /usr/share/wayland-sessions/plasma.desktop


# -- Disable the KCMs that we don't use.

DELETE_UNUSED_KCMS=(
    kcm_autostart.desktop
    kcm_breezedecoration.desktop
    kcm_desktoptheme.desktop
    kcm_feedback.desktop
    kcm_fontinst.desktop
    kcm_kwin_effects.desktop
    kcm_kwin_scripts.desktop
    kcm_kwin_virtualdesktops.desktop
    kcm_kwindecoration.desktop
    kcm_kwinoptions.desktop
    kcm_kwinrules.desktop
    kcm_kwintabbox.desktop
    kcm_kwinxwayland.desktop
    kcm_lookandfeel.desktop
    kcm_netpref.desktop
    kcm_nightlight.desktop
    kcm_notifications.desktop
    kcm_proxy.desktop
    kcm_regionandlang.desktop
    kcm_trash.desktop
    kcm_virtualkeyboard.desktop
    kcm_wallpaper.desktop
    kcm_webshortcuts.desktop
)

DELETE_UNUSED_SYSTEMSETTINGS_CATEGORIES=(
    settings-applications-defaults.desktop
    settings-applications-permissions.desktop
    settings-applications.desktop
    settings-hardware-display.desktop
    settings-hardware-input-pointing-devices.desktop
    settings-hardware-input-touchscreen.desktop
    settings-hardware-input.desktop
    settings-hardware-keyboard.desktop
    settings-hardware-multimedia.desktop
    settings-hardware-removable-storage.desktop
    settings-personalization.desktop
    settings-regionalsettings.desktop
    settings-root-category.desktop
    settings-security-privacy.desktop
    settings-system-administration.desktop
    settings-workspace-search.desktop
    settings-workspace-session.desktop
    settings-workspace-windowmanagement.desktop
    settings-workspace.desktop
)

rm -f  "${DELETE_UNUSED_KCMS[@]/#//usr/share/applications/}" "${DELETE_UNUSED_SYSTEMSETTINGS_CATEGORIES[@]/#//usr/share/systemsettings/categories/}"


# -- Remove Micro launcher.
#    -- Why the hell does a CLI text editor have a god damn desktop launcher to begin with?!

rm -f /usr/share/applications/micro.desktop


# -- Set QtGreet theme.

QTGREET_CONFIG="/etc/qtgreet/config.ini"

if [ -f "$QTGREET_CONFIG" ] && grep -q "Theme = default" "$QTGREET_CONFIG"; then
    sed -i 's|^Theme = default|Theme = nitrux|' "$QTGREET_CONFIG"
fi


# -- Create directories for aesthethic FHS.

BASE_DIR="/System"

declare -a DIRS=(
    "${BASE_DIR}/Boot"
    "${BASE_DIR}/Binaries/Administrative"
    "${BASE_DIR}/Binaries/Standard"
    "${BASE_DIR}/Binaries/Optional"
    "${BASE_DIR}/Configuration"
    "${BASE_DIR}/Devices"
    "${BASE_DIR}/Filesystems/External"
    "${BASE_DIR}/Filesystems/Internal"
    "${BASE_DIR}/Libraries"
    "${BASE_DIR}/Shareable"
    "${BASE_DIR}/Variable"
    "/Users"
)

for dir in "${DIRS[@]}"; do
    echo "Creating directory: $dir"
    mkdir -p "$dir" || echo "Failed to create $dir"
done


# -- Hide original FHS directories.

cp /configs/files/other/hidden /.hidden


# -- Mitigate Bluetooth devices disconnecting randomly.

MAIN_CONF="/etc/bluetooth/main.conf"
INPUT_CONF="/etc/bluetooth/input.conf"

if [ -f "$MAIN_CONF" ]; then
    sed -i \
        -e 's/^#DiscoverableTimeout = 0/DiscoverableTimeout = 0/' \
        -e 's/^#PairableTimeout = 0/PairableTimeout = 0/' \
        -e 's/^#ControllerMode = dual/ControllerMode = bredr/' \
        "$MAIN_CONF"
fi

if [ -f "$INPUT_CONF" ]; then
    sed -i 's/^#IdleTimeout=0/IdleTimeout=0/' "$INPUT_CONF"
fi


# -- Grab the latest clipvault release and drop it to a directory in PATH.

arch="$(uname -m)"
case "$arch" in
  x86_64|amd64) target="x86_64-unknown-linux-gnu" ;;
  aarch64|arm64) target="aarch64-unknown-linux-gnu" ;;
  *) echo "unsupported architecture: $arch"; exit 1 ;;
esac

tag="${CLIPVAULT_TAG:-latest}"
asset="clipvault-${target}.tar.gz"
base="https://github.com/Rolv-Apneseth/clipvault/releases"
url="$base/latest/download/$asset"
[ "$tag" = "latest" ] || url="$base/download/$tag/$asset"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$url" -o "$tmp/$asset"
else
  wget -qO "$tmp/$asset" "$url"
fi

tar -C "$tmp" -xf "$tmp/$asset"

binpath="$(find "$tmp" -type f -name clipvault -perm -u+x | head -n1)"
[ -n "$binpath" ] || { echo "clipvault binary not found in archive"; exit 1; }

install -m 0755 "$binpath" /usr/bin/clipvault
