#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu

# -- Source useful functions.
# shellcheck source=/dev/null

source /configs/scripts/others/misc-funcs


# -- Add casper configuration.

cat /configs/files/casper_files/casper.conf > /etc/casper.conf


# -- Use our configuration for adduser because Debian's broken for some reason.

cat /configs/files/other/adduser.conf > /etc/adduser.conf


# -- Replace elogind default configuration.

cat /configs/files/elogind_files/logind.conf > /etc/elogind/logind.conf
cat /configs/files/elogind_files/sleep.conf > /etc/elogind/sleep.conf
cat /configs/files/elogind_files/10-elogind.conf > /etc/elogind/sleep.conf.d/10-elogind.conf


# -- Replace pam.d files with our hardened files.

cat /configs/files/other/pam.d/common-password > /etc/pam.d/common-password
cat /configs/files/other/pam.d/common-auth > /etc/pam.d/common-auth
cat /configs/files/other/pam.d/common-account > /etc/pam.d/common-account


# -- Replace pwquality.conf.

cat /configs/files/other/pwquality.conf > /etc/security/pwquality.conf


# -- Add GRUB configuration.

cat /configs/files/grub_files/grub > /etc/default/grub


# -- Add motd.

cat /configs/files/other/motd > /etc/motd
