#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source useful functions.
# shellcheck source=/dev/null

source /configs/scripts/others/misc-funcs


# -- Add casper configuration.

cat /configs/files/casper_files/casper.conf > /etc/casper.conf


# -- Use our configuration for adduser because Debian's broken for some reason.

cat /configs/files/other/adduser.conf > /etc/adduser.conf


# -- Replace pam.d files with our hardened files.

cat /configs/files/other/pam.d/common-account > /etc/pam.d/common-password
cat /configs/files/other/pam.d/common-auth > /etc/pam.d/common-auth
cat /configs/files/other/pam.d/common-password > /etc/pam.d/common-password
cat /configs/files/other/pam.d/common-session > /etc/pam.d/common-session

cat /configs/files/other/security/limits.conf > /etc/security/limits.conf


# -- Replace pwquality.conf.

cat /configs/files/other/pwquality.conf > /etc/security/pwquality.conf


# -- Add default GRUB configuration.
#    -- Calamares replaces these values during installation.
#       -- GRUB_DISTRIBUTOR
#       -- GRUB_CMDLINE_LINUX_DEFAULT

cat /configs/files/grub_files/default/grub > /etc/default/grub


# -- Add motd.

cat /configs/files/other/motd > /etc/motd
