#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add Live user.
#
# -- We need to add the package because casper decided not to create the fkn user.

NX_LIVE_USER='
    nitrux-live-user
'

install $NX_LIVE_USER
