#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2024> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu


# -- Add GRUB and casper configuration.

rm \
	/etc/default/grub \
	/etc/casper.conf

cat /configs/files/grub_files/grub > /etc/default/grub
cat /configs/files/conf/casper.conf > /etc/casper.conf


# -- Add motd.

cat /configs/files/other/motd > /etc/motd


# -- Use our configuration for adduser because Debian's broken for some reason.

cat /configs/files/conf/adduser.conf > /etc/adduser.conf


# -- Add variable to PAM for Firefox to work with touchscreens in Wayland.

sed -i "$ a \  " /etc/security/pam_env.conf
sed -i "$ a #  Make Firefox work with touchscreens in Wayland" /etc/security/pam_env.conf
sed -i "$ a MOZ_ENABLE_WAYLAND DEFAULT=0 OVERRIDE=1" /etc/security/pam_env.conf


# -- Replace dnscrypt-proxy default configuration.

cat /configs/files/other/dnscrypt-proxy-settings/dnscrypt-proxy.toml > /etc/dnscrypt-proxy/dnscrypt-proxy.toml

$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md /var/cache/dnscrypt-proxy/public-resolvers.md
$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md.minisig /var/cache/dnscrypt-proxy/public-resolvers.md.minisig


# -- Replace common-password.
# -- Increase size of hashing rounds in /etc/pam.d/common-password. See https://cisofy.com/lynis/controls/AUTH-9230/

$(which cp) /configs/files/other/common-password /etc/pam.d/common-password


# -- Add pwquality.conf (which is missing for some reason!).

$(which cp) /configs/files/conf/pwquality.conf /etc/security/pwquality.conf


# -- Add user for AIDE (which is missing for some reason!).
# -- Replace aide.conf and 10_aide_hostname.

if id -u _aide >/dev/null 2>&1; then
    echo "User _aide already exists."
else
    useradd -r -s /bin/false -M _aide
    echo "User _aide created successfully."
fi

usermod -L _aide

$(which cp) /configs/files/conf/aide.conf /etc/aide/aide.conf
$(which cp) /configs/files/other/10_aide_hostname /etc/aide/aide.conf.d/10_aide_hostname


# -- Enable using a fingerprint sensor in SDDM.

sed -i '/#%PAM-1.0/a \\n# Use either a password or a fingerprint\nauth \t\t[success=1 new_authtok_reqd=1 default=ignore]  \tpam_unix.so try_first_pass likeauth nullok\nauth \t\tsufficient  \tpam_fprintd.so' /etc/pam.d/sddm


# -- Add user for OpenRazer (which is missing for some reason!).

if id -u razer >/dev/null 2>&1; then
    echo "User razer already exists."
else
    useradd -r -s /bin/false -M razer
    echo "User razer created successfully."
fi

usermod -L razer


# -- Replace elogind default configuration.

$(which cp) /configs/files/other/elogind/logind.conf /etc/elogind/logind.conf
$(which cp) /configs/files/other/elogind/sleep.conf /etc/elogind/sleep.conf
$(which cp) /configs/files/other/elogind/sleep.conf.d/10-elogind.conf /etc/elogind/sleep.conf.d/10-elogind.conf


# -- Create var data archive for NUTS.

DISTRIB_RELEASE=$(grep 'DISTRIB_RELEASE' /etc/lsb-release | cut -d'=' -f2)

tar -cJf "var-lib-dpkg-$DISTRIB_RELEASE.tar.xz" -P /var/lib/dpkg/
