#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -eu

# -- Source useful functions.
# shellcheck source=/dev/null

source /configs/scripts/others/misc-funcs


# -- Manually check the contents and existence of files, links and directories using arrays.

FILE_ONWERSHIP_TO_CHECK=()

check_ownership "${FILE_ONWERSHIP_TO_CHECK[@]}"

FILE_CONTENT_TO_CHECK=(
    /etc/adduser.conf
    /etc/casper.conf
    /etc/elogind/logind.conf
    /etc/elogind/logind.conf.d/10-logind.conf
    /etc/elogind/logind.conf.d/99-nitrux-logind.conf
    /etc/elogind/sleep.conf
    /etc/elogind/sleep.conf.d/10-sleep.conf
    /etc/elogind/sleep.conf.d/99-nitrux-sleep.conf
    /etc/greetd/config.toml
    /etc/initramfs-tools/modules
    /etc/plymouth/plymouthd.conf
    /usr/share/initramfs-tools/scripts/casper-bottom/15autologin
)

check_file_contents "${FILE_CONTENT_TO_CHECK[@]}"

FILE_TO_CHECK=()

check_files "${FILE_TO_CHECK[@]}"

LINKS_TO_CHECK=(
    /usr/share/plymouth/themes/default.plymouth
    /usr/share/plymouth/themes/text.plymouth
    /usr/share/plymouth/themes/bgrt.plymouth
)

check_symlinks "${LINKS_TO_CHECK[@]}"

DIRECTORIES_TO_CHECK=()

check_directories "${DIRECTORIES_TO_CHECK[@]}"


# -- Check the size of the initramfs.

check_initramfs_size


# -- Search the initramfs for something.

search_initramfs_for plymouth
search_initramfs_for crypttab


# -- Check that the Live user password is not goddamn empty.

if ! check_live_user_password; then
    echo "Live user password is missing or blank"
    exit 1
fi


# -- Check dkms status

dkms status
