#! /bin/bash

set -xe

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


rm \
	/etc/apt/preferences \
	/etc/apt/sources.list \
	/etc/apt/sources.list.d/* \
	/usr/share/keyrings/nitrux-repo.gpg \
	/usr/share/keyrings/nitrux-compat.gpg \
	/usr/share/keyrings/nitrux-testing.gpg

update


#	Unhold initramfs and casper packages.

INITRAMFS_CASPER_PKGS='
	casper
	initramfs-tools
	initramfs-tools-core
	initramfs-tools-bin
'

unhold $INITRAMFS_CASPER_PKGS
