#! /bin/bash

set -xe


rm \
	/etc/default/grub \
	/etc/casper.conf

cat /configs/files/grub_files/grub > /etc/default/grub
cat /configs/files/conf/casper.conf > /etc/casper.conf

rm \
	/boot/{vmlinuz,initrd.img,vmlinuz.old,initrd.img.old} || true

cat /configs/files/other/motd > /etc/motd

printf '%s\n' fuse nvidia amdgpu i915 exfat loop >> /etc/modules

cat /configs/files/conf/adduser.conf > /etc/adduser.conf

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


#	For some (very stupid) reason, checkinstall fails to include the symlinks for the MauiKit Frameworks libraries in the Debian packages
#	rendering the apps and the shell unusable, so *we* must add them manually.

#	MauiKit FileBrowsing 2.2.2.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so

#	MauiKit TextEditor 2.2.2.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so

#	MauiKit ImageTools 2.2.2.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so

#	MauiKit Accounts 2.2.2.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2.2.2 /usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2.2.2 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so

#	MauiKit Documents 1.0.1.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1.0.1 /usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1.0.1 /usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1.0.1 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1.0.1 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so

#	MauiKit Calendar 1.0.1.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1.0.1 /usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1.0.1 /usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1.0.1 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1.0.1 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so

#	MauiKit Terminal 1.0.0.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1.0.0 /usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1
ln -svf /usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1.0.0 /usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1.0.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1.0.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so

#	Maui Core Libraries 0.6.0.

ln -svf /usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0
ln -svf /usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so

ln -svf /usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0
ln -svf /usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so

ln -svf /usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0
ln -svf /usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0.6.0 /usr/lib/x86_64-linux-gnu/libMauiCorePower.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so

ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0
ln -svf /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0.6.0 /usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so


#	FIXME
#	Also link the library files for cask to launch because maui-shell and cask-server used Jammy for compilation, and the frameworks used Debian.
#	KDE PIM libraries were renamed to different SO names because of course they were. Update the links on every new release.

# ln -svf /usr/lib/x86_64-linux-gnu/libKPim5EventViews.so.5.23.0 /usr/lib/x86_64-linux-gnu/libKF5EventViews.so.5abi1
# ln -svf /usr/lib/x86_64-linux-gnu/libKPim5CalendarSupport.so.5.23.0 /usr/lib/x86_64-linux-gnu/libKF5CalendarSupport.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiCalendar.so.5.23.1 /usr/lib/x86_64-linux-gnu/libKF5AkonadiCalendar.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiWidgets.so.5.23.1 /usr/lib/x86_64-linux-gnu/libKF5AkonadiWidgets.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiCore.so.5.23.1 /usr/lib/x86_64-linux-gnu/libKF5AkonadiCore.so.5abi2
ln -svf /usr/lib/x86_64-linux-gnu/libKF5CalendarCore.so.5.105.0 /usr/lib/x86_64-linux-gnu/libKF5CalendarCore.so.5abi2


#	*And* create symlink for libboost-python for Calamares (from Neon) because it was compiled using Python 3.10 and we're using Python 3.11.

ln -svf /usr/lib/x86_64-linux-gnu/libboost_python311.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_python310.so.1.74.0


#	Move APT and dpkg out of the way, out of the way, move b...
#	use undebianize from Calamares to delete these files from the root.

mv /usr/bin/apt /opt/1
mv /usr/bin/apt-get /opt/2
mv /usr/bin/dpkg /opt/3

chmod -x /opt/{1,2,3}


#	Add link for applet window buttons.
#	NOTE: Update the link on every new release.

ln -sv /usr/lib/x86_64-linux-gnu/libkdecorations2private.so.5.27.5 /usr/lib/x86_64-linux-gnu/libkdecorations2private.so.9


#	Add link for libappimage1.0.

ln -sv /usr/lib/x86_64-linux-gnu/libappimage.so.1.0.3.abi1 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0


#	Enable Prelink.
#	Disable Prelink dpkg database timestamp.
#	Run prelink.

sed -i 's+PRELINKING=unknown+PRELINKING=yes+g' /etc/default/prelink
sed -i 's+PRELINK_NONRPM_CHECK_INTERVAL=7+PRELINK_NONRPM_CHECK_INTERVAL=0+g' /etc/default/prelink

prelink -amR


#	Enable ufw by default
#	Add rules for ports so Waydroid to access the Internet.

ufw enable
ufw allow 53
ufw allow 67
ufw default allow FORWARD


#	Add variable to PAM for Firefox to work with touchscreens in Wayland

sed -i "$ a \  " /etc/security/pam_env.conf
sed -i "$ a #  Make Firefox work with touchscreens in Wayland" /etc/security/pam_env.conf
sed -i "$ a MOZ_ENABLE_WAYLAND DEFAULT=0 OVERRIDE=1" /etc/security/pam_env.conf


#	Replace dnscrypt-proxy default configuration.

cat /configs/files/other/dnscrypt-proxy-settings/dnscrypt-proxy.toml > /etc/dnscrypt-proxy/dnscrypt-proxy.toml

$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md /var/cache/dnscrypt-proxy/public-resolvers.md
$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md.minisig /var/cache/dnscrypt-proxy/public-resolvers.md.minisig


#   Make sddm.conf immutable so nothing fucking touches it, did you hear casper?

chattr +i /etc/sddm.conf
