#! /bin/bash

set -e


#	Remove kernel from boot.

rm \
	/boot/{vmlinuz,initrd.img,vmlinuz.old,initrd.img.old} || true


#	Add Flathub.

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


# Function to create symlinks
create_symlink() {
    local source="$1"
    local destination="$2"

    ln -svf "$source" "$destination"
}


# Create symlinks for MauiKit FileBrowsing 2.2.2
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitFileBrowsing.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/filebrowsing/libMauiKitFileBrowsing.so"


# Create symlinks for MauiKit TextEditor 2.2.2
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitTextEditor.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/texteditor/libMauiKitTextEditor.so"


# Create symlinks for MauiKit ImageTools 2.2.2
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitImageTools.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/imagetools/libMauiKitImageTools.so"


# Create symlinks for MauiKit Accounts 2.2.2
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so.2.2.2" "/usr/lib/x86_64-linux-gnu/libMauiKitAccounts.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so.2.2.2" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/accounts/libMauiKitAccounts.so"


# Create symlinks for MauiKit Documents 1.0.1
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1.0.1" "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so.1.0.1" "/usr/lib/x86_64-linux-gnu/libMauiKitDocuments.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1.0.1" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so.1.0.1" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/documents/libMauiKitDocuments.so"


# Create symlinks for MauiKit Calendar 1.0.1
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1.0.1" "/usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so.1.0.1" "/usr/lib/x86_64-linux-gnu/libMauiKitCalendar.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1.0.1" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so.1.0.1" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/calendar/libMauiKitCalendar.so"


# Create symlinks for MauiKit Terminal 1.0.0
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so.1.0.0" "/usr/lib/x86_64-linux-gnu/libMauiKitTerminal.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1.0.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so.1.0.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauikit/terminal/libMauiKitTerminal.so"


# Create symlinks for Maui Core Libraries 0.6.0
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCoreAudio.so"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCoreNotifications.so"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/libMauiCorePower.so.0.6.0" "/usr/lib/x86_64-linux-gnu/libMauiCorePower.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/audio/libMauiCoreAudio.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/notifications/libMauiCoreNotifications.so"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0"
create_symlink "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so.0.6.0" "/usr/lib/x86_64-linux-gnu/qt5/qml/org/mauicore/power/libMauiCorePower.so"


#	FIXME
#	Also link the library files for cask to launch because maui-shell and cask-server used Jammy for compilation, and the frameworks used Debian.
#	KDE PIM libraries were renamed to different SO names because of course they were. Update the links on every new KF5 release.

KDEPIM_LIB="5.23.2"
KF5_LIB="5.107.0"

ln -svf /usr/lib/x86_64-linux-gnu/libKPim5EventViews.so.$KDEPIM_LIB /usr/lib/x86_64-linux-gnu/libKF5EventViews.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5CalendarSupport.so.$KDEPIM_LIB /usr/lib/x86_64-linux-gnu/libKF5CalendarSupport.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiCalendar.so.$KDEPIM_LIB /usr/lib/x86_64-linux-gnu/libKF5AkonadiCalendar.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiWidgets.so.$KDEPIM_LIB /usr/lib/x86_64-linux-gnu/libKF5AkonadiWidgets.so.5abi1
ln -svf /usr/lib/x86_64-linux-gnu/libKPim5AkonadiCore.so.$KDEPIM_LIB /usr/lib/x86_64-linux-gnu/libKF5AkonadiCore.so.5abi2
ln -svf /usr/lib/x86_64-linux-gnu/libKF5CalendarCore.so.$KF5_LIB /usr/lib/x86_64-linux-gnu/libKF5CalendarCore.so.5abi2


#	*And* create symlink for libboost-python for Calamares (from Neon) because it was compiled using Python 3.10 and we're using Python 3.11.

ln -svf /usr/lib/x86_64-linux-gnu/libboost_python311.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_python310.so.1.74.0


#	Move APT and dpkg out of the way, out of the way, move b...
#	use undebianize from Calamares to delete these files from the root.

mv /usr/bin/apt /opt/1
mv /usr/bin/apt-get /opt/2
mv /usr/bin/dpkg /opt/3

chmod -x /opt/{1,2,3}


#	Add link for applet window buttons.
#	NOTE: Update the link on every new release of Plasma.

PLASMA_LIB="5.27.6"

ln -sv /usr/lib/x86_64-linux-gnu/libkdecorations2private.so.$PLASMA_LIB /usr/lib/x86_64-linux-gnu/libkdecorations2private.so.9


#	Add link for libappimage1.0.

ln -sv /usr/lib/x86_64-linux-gnu/libappimage.so.1.0.3.abi1 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0


#	Enable ufw by default.
#	Add rules for ports so Waydroid to access the Internet.

ufw enable
ufw allow 53
ufw allow 67
ufw default allow FORWARD


#	Force SDDM to use Wayland session.

mv /usr/share/xsessions/plasma.desktop /usr/share/xsessions/orig.plasma.desktop.bak


#	Enable SELinux and set enforcing mode.

# selinux-activate
# selinux-config-enforcing
