#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2023-2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                              #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

set -eu


# -- Functions.

check_ownership() {
  local FILE_TO_CHECK=$1
  echo -e "\nChecking ownership of $FILE_TO_CHECK..."

  if [ -e "$FILE_TO_CHECK" ]; then
    local owner
    local group
    owner=$(stat -c "%U" "$FILE_TO_CHECK")
    group=$(stat -c "%G" "$FILE_TO_CHECK")
    echo "The file is owned by: $owner (Group: $group)"
  else
    echo "File $FILE_TO_CHECK does not exist."
  fi
}

check_file_contents() {
  local FILE=$1
  if [ -f "$FILE" ]; then
    echo "Contents of $FILE:"
    echo "=========================="
    cat "$FILE"
    echo "=========================="
  else
    echo "Error: File '$FILE' not found."
  fi
}

check_files() {
  local FILES=("$@")
  echo "Checking existence of files..."
  for FILE in "${FILES[@]}"; do
    if [ -e "$FILE" ]; then
      echo "File $FILE exists."
    else
      echo "File $FILE does not exist."
    fi
  done
}

check_symlinks() {
  local LINKS=("$@")
  echo -e "\nChecking symbolic link targets..."
  for LINK in "${LINKS[@]}"; do
    local TARGET
    TARGET=$(readlink -f "$LINK" || true)
    if [ -n "$TARGET" ]; then
      echo "Link $LINK points to: $TARGET"
    else
      echo "Link $LINK does not exist or is not a symbolic link."
    fi
  done
}

check_directories() {
  local DIRECTORIES=("$@")
  echo -e "\nChecking existence of directories..."
  if ! command -v tree &> /dev/null; then
    echo "Error: 'tree' command not found. Please install 'tree' to list directory contents."
    return 1
  fi
  for DIRECTORY in "${DIRECTORIES[@]}"; do
    if [ -d "$DIRECTORY" ]; then
      echo "Directory $DIRECTORY exists. Contents:"
      tree -L 2 "$DIRECTORY"
    else
      echo "Directory $DIRECTORY does not exist."
    fi
  done
}

check_initramfs_size() {
  local INITRAMFS_FILE
  INITRAMFS_FILE="/boot/initrd.img-$(uname -r)"

  if [ -f "$INITRAMFS_FILE" ]; then
    echo "Initramfs file: $INITRAMFS_FILE"
    echo "Initramfs size (actual disk usage):"
    
    du -h --apparent-size "$INITRAMFS_FILE" | awk '{printf "%.1fM\n", $1}'

    echo "15 largest files in initramfs:"
    lsinitramfs -l "$INITRAMFS_FILE" | sort -rh -k5 | head -n 15 | awk '{printf "%.1fM %s %s\n", $5/1024/1024, $3, $NF}'
  else
    echo "Error: Initramfs file '$INITRAMFS_FILE' not found inside chroot."
    echo "Available initramfs images in /boot:"
    ls -lh /boot/initrd.img-* 2>/dev/null || echo "No initramfs images found."
  fi
}


# -- Manually check the existence of files, links and directories using arrays.

FILE_ONWERSHIP_TO_CHECK=()

check_ownership "${FILE_ONWERSHIP_TO_CHECK[@]}"

FILE_CONTENT_TO_CHECK=(
  /usr/share/initramfs-tools/scripts/casper-bottom/15autologin
)

check_file_contents "${FILE_CONTENT_TO_CHECK[@]}"

FILE_TO_CHECK=()

check_files "${FILE_TO_CHECK[@]}"

LINKS_TO_CHECK=()

check_symlinks "${LINKS_TO_CHECK[@]}"

DIRECTORIES_TO_CHECK=()

check_directories "${DIRECTORIES_TO_CHECK[@]}"


# -- Check the size of the initramfs.

check_initramfs_size
