#! /bin/bash

set -xe


#	Add GRUB and casper configuration.

rm \
	/etc/default/grub \
	/etc/casper.conf

cat /configs/files/grub_files/grub > /etc/default/grub
cat /configs/files/conf/casper.conf > /etc/casper.conf


#	Add motd.

cat /configs/files/other/motd > /etc/motd


#	Add modules to load at boot time.

printf '%s\n' fuse nvidia nvidia_drm nvidia_modeset amdgpu i915 exfat loop >> /etc/modules


#	Add modules to initramfs.

printf '%s\n' hv_vmbus hv_storvsc hv_blkvsc hv_netvsc exfat >> /etc/initramfs-tools/modules


#	Use our configuration for adduser because Debian's broken for some reason.

cat /configs/files/conf/adduser.conf > /etc/adduser.conf


#	Enable Prelink.
#	Disable Prelink dpkg database timestamp.
#	Run prelink.

sed -i 's+PRELINKING=unknown+PRELINKING=yes+g' /etc/default/prelink
sed -i 's+PRELINK_NONRPM_CHECK_INTERVAL=7+PRELINK_NONRPM_CHECK_INTERVAL=0+g' /etc/default/prelink

prelink -amR


#	Add variable to PAM for Firefox to work with touchscreens in Wayland.

sed -i "$ a \  " /etc/security/pam_env.conf
sed -i "$ a #  Make Firefox work with touchscreens in Wayland" /etc/security/pam_env.conf
sed -i "$ a MOZ_ENABLE_WAYLAND DEFAULT=0 OVERRIDE=1" /etc/security/pam_env.conf


#	Replace dnscrypt-proxy default configuration.

cat /configs/files/other/dnscrypt-proxy-settings/dnscrypt-proxy.toml > /etc/dnscrypt-proxy/dnscrypt-proxy.toml

$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md /var/cache/dnscrypt-proxy/public-resolvers.md
$(which cp) /configs/files/other/dnscrypt-proxy-settings/public-resolvers.md.minisig /var/cache/dnscrypt-proxy/public-resolvers.md.minisig


#	Replace common-password.
#	Increase size of hashing rounds in /etc/pam.d/common-password. See https://cisofy.com/lynis/controls/AUTH-9230/

$(which cp) /configs/files/other/common-password /etc/pam.d/common-password


#	Add pwquality.conf (which is missing for some reason!).

$(which cp) /configs/files/conf/pwquality.conf /etc/security/pwquality.conf


#	Add user for AIDE (which is missing for some reason!).
#	Replace aide.conf and 10_aide_hostname.

if id -u _aide >/dev/null 2>&1; then
    echo "User _aide already exists."
else
    useradd -r -s /bin/false -M _aide
    echo "User _aide created successfully."
fi

usermod -L _aide

$(which cp) /configs/files/conf/aide.conf /etc/aide/aide.conf
$(which cp) /configs/files/other/10_aide_hostname /etc/aide/aide.conf.d/10_aide_hostname
