#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


echo "Checking existence of files..."
files_to_check=(
  "/etc/rc.local"
  "/etc/init.d"
  "/etc/sddm.conf.d"
  "/installed_pkgs*.txt"
)

for file in "${files_to_check[@]}"; do
  if ls "$file" &> /dev/null; then
    echo "File $file exists."
  else
    echo "File $file does not exist."
  fi
done

echo -e "\nChecking symbolic link targets..."
links_to_check=(
  "/vmlinuz"
  "/initrd.img"
  "/sbin/init"
  "/bin/sh"
)

for link in "${links_to_check[@]}"; do
  target=$(readlink -f "$link")
  if [ -n "$target" ]; then
    echo "Link $link points to: $target"
  else
    echo "Link $link does not exist or is not a symbolic link."
  fi
done

echo -e "\nChecking ownership of /usr/lib/dbus-1.0/dbus-daemon-launch-helper..."
file_to_check="/usr/lib/dbus-1.0/dbus-daemon-launch-helper"

if [ -e "$file_to_check" ]; then
  owner=$(stat -c "%U" "$file_to_check")
  echo "The file is owned by: $owner"
else
  echo "File $file_to_check does not exist."
fi

tree -L 2 \
	/Applications \
	/boot \
	/kboot \
	/etc/runlevels/{boot,default,nonetwork,off,recovery,shutdown,sysinit}
