#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


ls -lh \
	/boot \
	/etc/runlevels/{boot,default,nonetwork,off,recovery,shutdown,sysinit} \
	/etc/rc.local \
	/{vmlinuz,initrd.img} \
	/etc/{init.d,sddm.conf.d} \
	/usr/lib/dbus-1.0/dbus-daemon-launch-helper \
	/installed_pkgs*.txt

tree \
	/Applications \
	/kboot

stat \
	/sbin/init \
	/bin/sh

