#! /bin/bash

set -e

#	Source APT commands as functions.
#	shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


echo "Checking existence of files..."
files_to_check=(
  "/etc/rc.local"
  "/installed_pkgs_end.txt"
  "/installed_pkgs_start.txt"
)

for file in "${files_to_check[@]}"; do
  if ls "$file" &> /dev/null; then
    echo "File $file exists."
  else
    echo "File $file does not exist."
  fi
done

echo -e "\nChecking symbolic link targets..."
links_to_check=(
  "/vmlinuz"
  "/initrd.img"
  "/sbin/init"
  "/bin/sh"
)

for link in "${links_to_check[@]}"; do
  target=$(readlink -f "$link")
  if [ -n "$target" ]; then
    echo "Link $link points to: $target"
  else
    echo "Link $link does not exist or is not a symbolic link."
  fi
done

echo -e "\nChecking ownership of /usr/lib/dbus-1.0/dbus-daemon-launch-helper..."
file_to_check="/usr/lib/dbus-1.0/dbus-daemon-launch-helper"

if [ -e "$file_to_check" ]; then
  owner=$(stat -c "%U" "$file_to_check")
  group=$(stat -c "%G" "$file_to_check")
  echo "The file is owned by: $owner (Group: $group)"
else
  echo "File $file_to_check does not exist."
fi

echo -e "\nChecking existence of directories..."
directories_to_check=(
  "/Applications"
  "/boot"
  "/kboot"
  "/etc/runlevels/boot"
  "/etc/runlevels/default"
  "/etc/runlevels/nonetwork"
  "/etc/runlevels/off"
  "/etc/runlevels/recovery"
  "/etc/runlevels/shutdown"
  "/etc/runlevels/sysinit"
  "/etc/sddm.conf.d"
)

for directory in "${directories_to_check[@]}"; do
  if [ -d "$directory" ]; then
    echo "Directory $directory exists. Contents:"
    tree -L 2 "$directory"
  else
    echo "Directory $directory does not exist."
  fi
done

check_file_contents() {
    if [ -f "$1" ]; then
        echo "Contents of $1:"
        echo "=========================="
        tail -n +1 "$1"
        echo "=========================="
    else
        echo "Error: File '$1' not found."
    fi
}

check_file_contents "/etc/sddm.conf.d/kde_settings.conf"
check_file_contents "/etc/sddm.conf"
