#! /bin/sh

# - - - Create the basic workspace.

/bin/busybox mkdir -p /proc /sys /dev /bin /sbin /usr/bin /usr/sbin /iso

/bin/busybox --install -s

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

# - - - Hide kernel messages.

dmesg -n 1

# - - - Mount basic filesystems.

mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M none /dev
mount -t proc -o noexec,nosuid,nodev  none /proc
mount -t sysfs -o noexec,nosuid,nodev none /sys

mkdir -p /dev/pts
mount -t devpts none /dev/pts

mkdir -p /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec none /dev/shm

# - - - Helper functions.

say () { echo -e "\e[32m  $@ \e[0m"; }
err () { echo -e "\e[31m# $@ \e[0m"; }

panic () { err "$@"; setsid cttyhack sh; }

# - - - Find the root filesystem.

say "Trying to mount the data partition..."

for attempt in 1 2 3 4 5; do
	disk=$(findfs LABEL="ROOTFILESYSTEM")
	mount -t iso9660 "$disk" /iso && break || sleep 1
done

# - - - Mount the root filesystem as an overlay filesystem.

say "Mounting the root filesystem as an overlay filesystem"

mkdir -p \
	/media/root-ro \
	/media/root-rw \
	/newroot/media/root-ro \
	/newroot/media/root-rw

mount -t squashfs -o ro /iso/rootfs.sfs /media/root-ro

mount -t tmpfs root-tmpfs /media/root-rw

mkdir -p \
	/media/root-rw/work \
	/media/root-rw/root

mount -t overlay -o lowerdir=/media/root-ro,upperdir=/media/root-rw/root,workdir=/media/root-rw/work none /newroot

# - - - It's time to switch to `/newroot`.

cat /proc/mounts | while read DEV DIR TYPE OPTS; do
	if [ "$DIR" != "/" -a "$DIR" != "/newroot" -a -d "$DIR" ]; then
		mkdir -p /newroot/$DIR
		mount -o move $DIR /newroot/$DIR
	fi
done

sync

exec /bin/busybox switch_root /newroot /sbin/init

panic "Unable to switch root."
