#! /bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin


# - - - KERNEL, SHUT UP..!

dmesg -n 1

printf "\e[34m

##   ## ##   ##  #####   #####
###  ##  ## ##  ### ### ###  ##
#### ##   ###   ##   ##  ###
## ####   ###   ##   ##    ###
##  ###  ## ##  ### ### ##  ###
##   ## ##   ##  #####   #####  \e[36mv0.1.1-\e[31mBETA \e[0m

"


# - - - MOUNT BASIC FILESYSTEMS.

mount -t devtmpfs -o size=5M none /dev
mount -t proc   none /proc
mount -t sysfs  none /sys

mkdir -p /dev/pts
mount -t devpts none /dev/pts

if [ -e /sys/firmware/efi ]; then
	mount -t efivarfs efivarfs /sys/firmware/efi/efivars -o nosuid,nodev,noexec
fi


# - - - FROM HERE IT'S SAFE TO INSERT CODE.

# - - - *.

say () { printf "\n\e[32m  # # # $@ \e[0m\n"; }
err () { printf "\n\e[31m  # # # $@ \e[0m\n"; }

panic () {
	err "$@"
	err "A COMMAND LINE HAS BEEN STARTED. GOOD LUCK. :("
	exec setsid cttyhack sh
}


# - - - LOAD MODULES (DRIVERS).

find /sys -name modalias -exec cat \{\} + |
awk '
   { aliases[$0] = 1 }
   END {
	  for (alias in aliases) {
		 print alias
	  }
   }
' > modaliases.lst

mdev -s

[ -e /proc/sys/kernel/hotplug ] && echo /sbin/mdev > /proc/sys/kernel/hotplug

while read -r modalias; do
   modprobe ${modalias} 2> /dev/null
done < modaliases.lst


# - - - FIND THE ROOT FILESYSTEM.

say "TRYING TO MOUNT DATA PARTITION..."

# wait up to five seconds to mount the data partition.

for attempt in 1 2 3 4 5; do
	sleep 1
	disk=$(findfs LABEL="ROOTFILESYSTEM")

	if mount "$disk" /mnt/; then
		say 'MOUNTED DATA PARTITION ON `/mnt/`'
		break
	fi
done


# - - - MOUNT THE ROOT FLESYSTEM AS AN OVERLAYFS.

mkdir -p \
	/overlay       \
	/overlay/lower \
	/overlay/upper \
	/overlay/work

mount -o ro /mnt/rootfs.sfs /overlay/lower/ && say "MOUNTED /overlay/lower"

mount -t tmpfs -o size=20%,mode=1777 none /overlay/upper && say "MOUNTED /overlay/upper"

ld=/overlay/lower ud=/overlay/upper wd=/overlay/workdir

mount -t overlay -o lowerdir="$ld",upperdir="$ud",workdir="$wd" none /overlay/upper


# - - - STOP MDEV.

# Remove the kernel hotplug handler.
[ -e /proc/sys/kernel/hotplug ] && echo > /proc/sys/kernel/hotplug

# Wait until all mdev processes have quit.
while pids=$(pidof mdev); do
	kill -TERM ${pids} 2> /dev/null
	sleep 0.1
done


# - - - IT'S TIME TO SWITCH ROOT. 

say "SWITCHING TO REAL ROOT"

mount -o move /sys  /overlay/upper/sys &&
mount -o move /dev  /overlay/upper/dev &&
mount -o move /tmp  /overlay/upper/tmp &&
mount -o move /proc /overlay/upper/proc

exec switch_root /overlay/upper /sbin/init


# - - - IF THE FOLLOWING GETS EXECUTED, THAT MEANS A REALLY NASTY ERROR OCCURED.

panic "UNABLE TO SWITCH TO REAL ROOT"
