#!/usr/bin/env sh

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

set -e


# -- Restart NetworkManager only after resuming from suspend.

sleep 2

case "$1" in
  post)
    IFACES=$(nmcli -t -f DEVICE,TYPE,STATE dev | awk -F: '$3=="connected" { print $1 }')
    if [ -n "$IFACES" ]; then
      logger -t nm-hook "Interface(s) detected: $IFACES — restarting NetworkManager"
      rc-service network-manager-openrc restart
    else
      logger -t nm-hook "No connected interfaces — NetworkManager not restarted"
    fi
    ;;
esac
