#!/bin/sh

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

PREREQ=""

prereqs() {
    echo "${PREREQ}"
}

case "$1" in
    prereqs) prereqs; exit 0 ;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# -- Begin real processing below this line

cp /etc/crypttab "${DESTDIR}/cryptroot/crypttab"
