#!/bin/sh

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>

PREREQ=""

prereqs() {
    echo "${PREREQ}"
}

case "$1" in
    prereqs) prereqs; exit 0 ;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# -- Begin real processing below this line

THEME_NAME="$(awk -F= '/^[[:space:]]*Theme=/ && $0 !~ /^#/ { gsub(/[[:space:]]/, "", $2); print $2 }' /etc/plymouth/plymouthd.conf)"
THEME_DIR="/usr/share/plymouth/themes/${THEME_NAME}"

if [ -n "$THEME_NAME" ] && [ -d "$THEME_DIR" ]; then
  mkdir -p "${DESTDIR}/usr/share/plymouth/themes"
  cp -a "$THEME_DIR" "${DESTDIR}/usr/share/plymouth/themes/"
  echo ""
  echo "Included theme: $THEME_NAME" >&2
else
  echo "Theme not found or not set." >&2
fi
