#!/bin/sh

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

PREREQ=""

prereqs() {
	echo "${PREREQ}"
}

case "$1" in
	prereqs) prereqs; exit 0 ;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

THEMES="/usr/share/plymouth/themes"
PLYMOUTH_CONF="/etc/plymouth/plymouthd.conf"
PLYMOUTH_PLUGIN_PATH="$(plymouth --get-splash-plugin-path)"
ARCH_LIBDIR="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
DEST_PLYMOUTH="${DESTDIR}/usr/share/plymouth"
DEST_ETC="${DESTDIR}/etc"

if [ -r "${PLYMOUTH_CONF}" ]; then
	THEME_NAME="$(awk -F= '/^Theme=/ { gsub(/[[:space:]]/, "", $2); print $2 }' "$PLYMOUTH_CONF")"
else
	exit 0
fi

[ -z "$THEME_NAME" ] && exit 0

THEME="${THEMES}/${THEME_NAME}/${THEME_NAME}.plymouth"
[ ! -f "$THEME" ] && exit 0

MODULE_NAME="$(awk -F= '/^ModuleName=/ { gsub(/[[:space:]]/, "", $2); print $2 }' "$THEME")"
IMAGE_DIR="$(awk -F= '/^ImageDir=/ { gsub(/[[:space:]]/, "", $2); print $2 }' "$THEME")"
MODULE="${PLYMOUTH_PLUGIN_PATH}/${MODULE_NAME}.so"

[ ! -e "$MODULE" ] && { echo "W: plymouth module ($MODULE) missing, skipping."; exit 0; }

copy_exec "${MODULE}"
copy_exec /sbin/plymouthd
copy_exec /bin/plymouth
copy_exec /lib/plymouth/plymouthd-fd-escrow

PLUGINS="text.so details.so"
case "$THEME_NAME" in
	text|details|tribar) : ;;
	*) PLUGINS="${PLUGINS} label.so" ;;
esac

for plugin in $PLUGINS; do
	if [ -f "${PLYMOUTH_PLUGIN_PATH}/${plugin}" ]; then
		copy_exec "${PLYMOUTH_PLUGIN_PATH}/${plugin}"
	else
		echo "W: plymouth: plugin ${plugin} missing."
	fi
done

mkdir -p "${DESTDIR}/${THEMES}"
cp -r "${THEMES}/${THEME_NAME}" "${DESTDIR}/${THEMES}"

[ -n "$IMAGE_DIR" ] && [ "$IMAGE_DIR" != "${THEMES}/${THEME_NAME}" ] && cp -r "$IMAGE_DIR" "${DESTDIR}/${THEMES}"

cp -a "${THEMES}/details" "${DESTDIR}/${THEMES}" || true
cp -a "${THEMES}/text"    "${DESTDIR}/${THEMES}" || true

mkdir -p "${DEST_ETC}/plymouth"
[ -f "$PLYMOUTH_CONF" ] && cp -a "$PLYMOUTH_CONF" "${DEST_ETC}/plymouth/"
cp -a /usr/share/plymouth/plymouthd.defaults "${DEST_PLYMOUTH}/"

[ -f /etc/os-release ] && { mkdir -p "${DEST_ETC}"; cp /etc/os-release "${DEST_ETC}"; }

case "$THEME_NAME" in
	text|details) : ;;
	*)
		cp /usr/share/plymouth/debian-logo.png "${DEST_PLYMOUTH}/" || true

		mkdir -p "${DEST_ETC}/fonts/conf.d"
		cp -a /etc/fonts/fonts.conf "${DEST_ETC}/fonts/"
		cp -rL /etc/fonts/conf.d/60-latin.conf "${DEST_ETC}/fonts/conf.d/" || true

		# Fonts (DejaVu)
		for font in DejaVuSerif.ttf DejaVuSans.ttf; do
			src="/usr/share/fonts/truetype/dejavu/${font}"
			dst="${DESTDIR}/usr/share/fonts/truetype/dejavu"
			[ -f "$src" ] && { mkdir -p "$dst"; cp -a "$src" "$dst/"; }
		done

		case "$THEME_NAME" in
			spinner|bgrt)
				for font in Cantarell-Regular.otf Cantarell-Light.otf; do
					src="/usr/share/fonts/opentype/cantarell/${font}"
					dst="${DESTDIR}/usr/share/fonts/opentype/cantarell"
					[ -f "$src" ] && { mkdir -p "$dst"; cp -a "$src" "$dst/"; }
				done
				;;
		esac

		mkdir -p "${DESTDIR}/var/cache/fontconfig"
		mkdir -p "${DESTDIR}/usr/local/share/fonts"
		[ -x "$(command -v fc-cache)" ] && fc-cache -s -y "${DESTDIR}" >/dev/null 2>&1 || true

		[ -f /etc/default/keyboard ] && {
			mkdir -p "${DEST_ETC}/default"
			cp /etc/default/keyboard "${DEST_ETC}/default"
		}

		if grep -q "^ModuleName=two-step" "$THEME"; then
			logo="/usr/share/desktop-base/debian-logos/logo-text-version-64.png"
			[ -f "$logo" ] && cp "$logo" "${DESTDIR}/${IMAGE_DIR}/watermark.png"
		fi
		;;
esac

MODULES_EXCLUDE="mga r128 savage sis tdfx via panfrost"

# shellcheck disable=SC2153
case "$MODULES" in
	dep)
		for DRM_DEVICE in /sys/class/drm/*; do
			DRM_DEVICE="$(readlink -f "$DRM_DEVICE")" || continue
			MODULE_PATH="$(readlink -f "$DRM_DEVICE/device/driver/module")" || continue
			MODULE_NAME="$(basename "$MODULE_PATH")" || continue

			for m in $MODULES_EXCLUDE; do
				[ "$MODULE_NAME" = "$m" ] && continue 2
			done

			sys_walk_mod_add "$DRM_DEVICE" || echo "W: couldn't include modules for '$DRM_DEVICE'"
		done
		;;
	list)
		echo "W: plymouth: skipping DRM modules (MODULES=list)"
		;;
	*)
		# shellcheck disable=SC2086
		copy_modules_dir kernel/drivers/gpu/drm $MODULES_EXCLUDE
		;;
esac

copy_exec "/usr/lib/${ARCH_LIBDIR}/plymouth/renderers/frame-buffer.so" || true
copy_exec "/usr/lib/${ARCH_LIBDIR}/plymouth/renderers/drm.so" || true

mkdir -p "${DEST_ETC}"
grep -qs '^root:' "${DEST_ETC}/passwd" || echo "root:x:0:0:root:/root:/bin/sh" >> "${DEST_ETC}/passwd"
grep -qs '^passwd: files' "${DEST_ETC}/nsswitch.conf" || echo "passwd: files" >> "${DEST_ETC}/nsswitch.conf"


# shellcheck disable=SC2231
for lib in /lib/${ARCH_LIBDIR}/libnss_files*; do
	[ -e "$lib" ] || continue
	copy_exec "$lib"
done

