#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2023-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Exit on errors.

set -eu


# -- Variables.

GRUB_CFG="/boot/grub/grub.cfg"

#   ====== START ======

# -- Generate GRUB menu file.

grub-mkconfig -o "$GRUB_CFG" "$@"


# -- Generate backup GRUB menu file.

cp "$GRUB_CFG" "$GRUB_CFG.bak"


# -- Edit GRUB menu file and remove "ro" parameter.

sed -i 's/\bro\b//g' "$GRUB_CFG"

#   ====== END ======
