#!/bin/sh

PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

#   Use findfs to find the device name of the root partition based on its label.

ROOT_DEV=$(findfs LABEL=NX_ROOT)

#   If the root device is empty, exit with an error.

if [ -z "$ROOT_DEV" ]; then
    echo "Error: Unable to determine real root filesystem device."
    exit 1
fi

#   Attempt to determine the filesystem type of the root device.

ROOT_TYPE=$(blkid -o value -s TYPE "$ROOT_DEV")

#   If the filesystem type is empty, exit with an error.

if [ -z "$ROOT_TYPE" ]; then
    echo "Error: Unable to determine real root filesystem type."
    exit 1
fi

#   Mount the real root filesystem.

mount -t "$ROOT_TYPE" "$ROOT_DEV" /root
