# Empty listen_addresses to use systemd socket activation

listen_addresses = [':5300']
server_names = ['adguard-dns', 'adguard-dns-ipv6', 'ams-dnscrypt-nl', 'ams-dnscrypt-nl-ipv6']
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true
cache = true
require_dnssec = true

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'

[nx_log]
  file = '/var/log/dnscrypt-proxy/nx.log'

[sources]
  [sources.'public-resolvers']
  url = 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md'
  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
