#!/bin/sh
set -e

PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# Copy the file to the initramfs
copy_file /etc/crypttab /etc
