#!/bin/sh
set -e

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# -- Begin real processing below this line

OMIT_DRIVERS="nvidia.ko gsp-535.113.01.bin gsp_ga10x.bin gsp_tu10x.bin gsp-535.113.01.bin"
for i in ${OMIT_DRIVERS}; do
   find "${DESTDIR}" -name "${i}" -delete
done