#!/bin/sh
set -e

PREREQS=""
case $1 in
        prereqs) echo "${PREREQS}"; exit 0;;
esac

# shellcheck source=/dev/null
. /usr/share/initramfs-tools/hook-functions

# Copy the script to the initramfs
copy_exec /usr/bin/vfio-override /bin/
