# Default values for dnscrypt-proxy
# dnscrypt-proxy.toml 2025 (c) Nitrux Latinoamericana S.C.

# 1. BINDING
# We use 127.0.2.1 to avoid conflict with dnsmasq on 127.0.0.1
listen_addresses = ['127.0.0.1:5353', '[::1]:5353']

# 2. GENERAL SETTINGS
# Disable cache because NetworkManager(dnsmasq) is already doing it
cache = false
dnscrypt_servers = true
doh_servers = true
ipv4_servers = true
ipv6_servers = true
log_level = 2

# 3. PRIVACY & SECURITY RULES
require_dnssec = true
require_nolog = true
require_nofilter = false

# 4. SERVERS
# We prioritize AdGuard for blocking, Quad9 for malware protection
server_names = [
  'quad9-dnscrypt-ip4-filter-pri',
  'quad9-dnscrypt-ip6-filter-pri',
  'ahadns-doh-la'
]

# 5. ANONYMIZED DNS (Ready to enable)
# Uncomment the [anonymized_dns] section below to enable IP hiding.
# [anonymized_dns]
# routes = [
#     { server_name='adguard-dns', via=['anon-cs-fr', 'anon-cs-nl'] },
#     { server_name='quad9-dnscrypt-ip4-filter-pri', via=['anon-cs-fr', 'anon-cs-de'] }
# ]

# 6. REQUIRED SOURCES
[sources.'public-resolvers']
url = 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
