# Default values for dnscrypt-proxy
# dnscrypt-proxy.toml 2025 (c) Nitrux Latinoamericana S.C.

# 1. BINDING
listen_addresses = ['127.0.0.1:5353', '[::1]:5353']

# 2. GENERAL SETTINGS
# Disable cache because NetworkManager(dnsmasq) is already doing it.
cache = false
dnscrypt_servers = true
doh_servers = true
ipv4_servers = true
ipv6_servers = true
log_level = 2

# 3. PRIVACY & SECURITY RULES
require_dnssec = true
require_nolog = true
require_nofilter = false

# 4. SERVERS
# We prioritize AdGuard for blocking, Quad9 for malware protection.
server_names = [
  'adguard-dns-doh',
  'quad9-dnscrypt-ip4-filter-pri',
  'quad9-dnscrypt-ip6-filter-pri',
  'ahadns-doh-la'
]

# 5. ANONYMIZED DNS (Ready to enable)
# Define where to download the list of Relays.
[sources.'relays']
url = 'https://download.dnscrypt.info/resolvers-list/v2/relays.md'
cache_file = '/var/cache/dnscrypt-proxy/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''

# BEGIN AUTO ANONYMIZED DNS
[anonymized_dns]
skip_incompatible = true

# These routes relay traffic through France (fr) and Germany (de).
# Change the country codes (e.g., 'anon-cs-nl' for the Netherlands) if you want different locations.
routes = [
    { server_name='adguard-dns-doh', via=['anon-cs-fr', 'anon-cs-de'] },
    { server_name='quad9-dnscrypt-ip4-filter-pri', via=['anon-cs-fr', 'anon-cs-de'] }
]
# END AUTO ANONYMIZED DNS

# 6. REQUIRED SOURCES
[sources.'public-resolvers']
url = 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md'
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
