#!/bin/sh

PREREQ=""

prereqs()
{
	   echo "$PREREQ"
}

case $1 in
# get pre-requisites
	prereqs)
		   prereqs
		   exit 0
		   ;;
esac

. /scripts/casper-functions
. /scripts/lupin-helpers

iso_path=
for x in $(cat /proc/cmdline); do
	case ${x} in
		ZNX_DEV_UUID=*) znx_dev_uuid=${x#ZNX_DEV_UUID=};;
		iso-scan/filename=*) iso_path=${x#iso-scan/filename=};;
	esac
done

_find_dev () {
	lsblk -no PATH,UUID | grep $1 | cut -d ' ' -f 1
}

test "$iso_path" && test -f "$iso_path" && {
	znx_dev=$(_find_dev $znx_dev_uuid)
	mkdir -p /isodevice
	mount -t btrfs "$znx_dev" /isodevice && {
		echo "LIVEMEDIA=$iso_path" >> /conf/param.conf
		echo "FOUNDDEV=$znx_dev" >> /conf/param.conf
		echo "LIVEMEDIA_OFFSET=0" >> /conf/param.conf
	} || {
		panic "
Could not find the ISO $iso_path
This could also happen if the file system is not clean because of an operating
system crash, an interrupted boot process, an improper shutdown, or unplugging
of a removable device without first unmounting or ejecting it.
"
	}
}
