#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring fstab..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat > $FSTAB <<EOF
/boot /Core/Boot none defaults,bind 0 0
/cdrom /Core/Boot/ESP none defaults,bind 0 0
/dev /Devices none defaults,bind 0 0
/etc /System/Configuration none defaults,bind 0 0
/home /Users none defaults,bind 0 0
/isodevice /Core/System/Deployments none defaults,bind 0 0
/media /Devices/Removable none defaults,bind 0 0
/mnt /System/Mount/Filesystems none defaults,bind 0 0
/opt /System/Binaries/Optional none defaults,bind 0 0
/proc /System/Processes none defaults,bind 0 0
/run /System/Runtime none defaults,bind 0 0
/srv /System/Server/Services none defaults,bind 0 0
/sys /System/DevicesFS none defaults,bind 0 0
/tmp /System/TempFS none defaults,bind 0 0
/usr/bin  /System/Binaries none defaults,bind 0 0
/usr/lib  /System/Libraries none defaults,bind 0 0
/usr/share  /System/Resources/Shared none defaults,bind 0 0
/var  /System/Variable none defaults,bind 0 0
overlay / overlay rw 0 0
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

rm -f /root/etc/rcS.d/S*checkroot.sh

log_end_msg
