#! /bin/bash

set -xe

dpkg_force_remove () { /usr/bin/dpkg --remove --no-triggers --force-remove-essential --force-bad-path $@; }


#	Remove Debian bits.

REMOVE_DEB_BITS_PKGS='
	apt
	apt-transport-https
	apt-utils
'

dpkg_force_remove $REMOVE_DEB_BITS_PKGS


#   Remove dpkg directories.

REMOVE_DPKG='
    /etc/alternatives/README
    /etc/cron.daily/dpkg
    /etc/dpkg
    /etc/apt
    /etc/logrotate.d/alternatives
    /etc/logrotate.d/dpkg
    /usr/bin/dpkg
    /usr/bin/dpkg-*
    /usr/bin/update-alternatives
    /usr/libexec/dpkg
    /usr/share/doc/dpkg/
    /usr/share/dpkg/
    /usr/share/lintian/overrides/dpkg
    /usr/share/polkit-1/actions/org.dpkg.pkexec.update-alternatives.policy
    /var/lib/apt/lists
    /var/cache/apt
    /var/lib/dpkg/
    /opt/1
    /opt/2
    /opt/3
'

rm -rf ${REMOVE_DPKG//\\n/ } || true


#   Delete live user from root because idontfuckingknowwhy the postrm script in the package
#   doesn't actually do that, so let's brute force that.

deluser --remove-home nitrux

exit 0
