#! /bin/bash

set -xe

dpkg_force_remove () { /usr/bin/dpkg --remove --no-triggers --force-remove-essential --force-bad-path "$@"; }


#	Remove Debian bits.

REMOVE_DEB_BITS_PKGS='
	apt
	apt-transport-https
	apt-utils
'

dpkg_force_remove $REMOVE_DEB_BITS_PKGS


#   Remove dpkg directories.

REMOVE_DPKG='
    /etc/alternatives/README
    /etc/apt
    /etc/cron.daily/dpkg
    /etc/dpkg
    /etc/logrotate.d/alternatives
    /etc/logrotate.d/dpkg
    /lib/systemd/system/dpkg-db-backup.*
    /opt/1
    /opt/2
    /opt/3
    /usr/bin/dpkg
    /usr/bin/dpkg-*
    /usr/bin/update-alternatives
    /usr/lib/x86_64-linux-gnu/libapt-pkg.so.*
    /usr/libexec/dpkg
    /usr/sbin/dpkg-*
    /usr/share/doc/dpkg/
    /usr/share/doc/libapt-pkg6.0/
    /usr/share/dpkg/
    /usr/share/lintian/overrides/dpkg
    /usr/share/polkit-1/actions/org.dpkg.pkexec.update-alternatives.policy
    /var/cache/apt
    /var/lib/apt/lists
    /var/lib/dpkg/
'

rm -rf ${REMOVE_DPKG//\\n/ } || true


#   Delete translation files.

find /usr/share/locale/ -name 'dpkg.mo' -exec rm -f {} \;
find /usr/share/locale/ -name 'libapt-pkg6.0.mo' -exec rm -f {} \;


#   Delete live user from root because idontfuckingknowwhy the postrm script in the package
#   doesn't actually do that, so let's brute force that.

deluser --remove-home nitrux


#   "Fix" for https://github.com/Nitrux/nitrux-bug-tracker/issues/124

SRC="/etc/NetworkManager/system-connections"
DEST="/var/lib/NetworkManager/system-connections"

mkdir -p "$DEST"
mv "$SRC"/* "$DEST"/
rmdir "$SRC"
ln -sv "$DEST" "$SRC"

exit 0
