#! /bin/sh


# -- Settings.

TITLE="znx GUI."
STYLE=breeze


# -- Helper functions.

success () {
	kdialog \
		--style $STYLE \
		--title "$TITLE." \
		--msgbox "$1"
}

error () {
	kdialog \
		--style $STYLE \
		--title "$TITLE." \
		--error "$@"
}


# -- Verify if this script is running from a live session.

mountpoint -q /cdrom ||
	error "Not running in a live session. There's nothing to deploy."


# -- Ask for the target device.

TARGET_DEV=$(kdialog \
	--style $STYLE \
	--title "$TITLE" \
	--combobox "Select the target device to deploy the image." $(lsblk -npdlo NAME))


# -- Ask for the image name.

IMG_NAME=$(kdialog \
	--style $STYLE \
	--title "$TITLE" \
	--inputbox "Type a name for the image (e.g.: nitrux/stable, nitrux/development)." "nitrux/stable")


# -- Deploy the image.

kdialog \
	--style $STYLE \
	--title "$TITLE" \
	--passivepopup "Please wait while the installation finishes: you'll be notified."


MEDIA_PATH=$(grep /cdrom /proc/mounts | cut -d " " -f 1)

znx deploy $TARGET_DEV $IMG_NAME $MEDIA_PATH &&
	success "Successfully deployed the image." ||
	error "Failed to deploy the $IMG_NAME to $TARGET_DEV."
