#! /bin/sh


# -- Variables.

TITLE=ZNX_GUI
STYLE=breeze

set -x


# -- Functions for the GUI.

alias ui="kdialog --title='$TITLE'"

error () { ui --error "$@"; exit 1; }
notify () { ui --passivepopup "$@" 5; }
ask () { ui --yesno "$@"; }
as_root () { ui --password "Password:" | sudo -Sk $@; }

CMDS="init restore-esp deploy update revert remove clean reset stats"

select_command () { ui --combobox "Command to run:" $CMDS; }
select_device () { ui --combobox "Device:" $(lsblk -npdlo NAME); }
select_image () { ui --combobox "Image:" $(as_root znx list $DEVICE); }

get_url () { ui --inputbox "File to deploy (URL or path):"; }
get_image () { ui --inputbox "Image name:"; }


# -- Wrappers for znx's commands.

_znx_gui_init () { as_root znx init $DEVICE; }
_znx_gui_restore_esp () { as_root znx restore-esp $DEVICE; }
_znx_gui_deploy () { as_root znx deploy $DEVICE $(get_image) $(eval echo $(get_url)); }
_znx_gui_update () { as_root znx update $DEVICE $(select_image); }
_znx_gui_revert () { as_root znx revert $DEVICE $(select_image); }
_znx_gui_remove () { as_root znx remove $DEVICE $(select_image); }
_znx_gui_clean () { as_root znx clean $DEVICE $(select_image); }
_znx_gui_reset () { as_root znx reset $DEVICE $(select_image); }

_znx_gui_stats () {
    TMP_FILE=$(mktemp)
    as_root znx stats $DEVICE $(select_image) > $TMP_FILE
    ui --textbox $TMP_FILE
    rm -rf $TMP_FILE
}


# -- Loop until the user closes the main window.

while :; do

    COMMAND=$(select_command)

    [ ${#COMMAND} -gt 0 ] ||
        error "Operation cancelled."

    DEVICE=$(select_device)

    notify "Please wait. You will be notified when the command finishes." &

    _znx_gui_$COMMAND &&
        notify "Operation completed successfully." ||
        error "Operation failed!."

    ask "Do you want to perform another action?." ||
        exit

done
