#! /bin/sh

TITLE="ZNX Gui"

GetDevice () {
	echo $(kdialog \
		--style breeze \
		--title "$TITLE" \
		--combobox "Select the target device to deploy the image." $(lsblk -npdlo NAME))
}

GetName () {
	echo $(kdialog \
		--style breeze \
		--title "$TITLE" \
		--inputbox "Name of image (Ex : nitrux/rolling, nitrux/release_v1-01).")
}

GetPath () {
	echo $(kdialog \
		--style breeze \
		--title "$TITLE" \
		--inputbox "Full path or  web URL to ISO image or zsync file.")
}

showSuccess () {
	kdialog \
		--style breeze \
		--title "Success - $TITLE" \
		--msgbox "$1"
}

showUnexpectedError () {
	kdialog \
		--style breeze \
		--title "Error - $TITLE" \
		--error "Unexpected Error Occurred. Run this software in a Terminal for more details."
}

showProgressDialog () {
	kdialog \
		--title "$TITLE" \
		--style breeze \
		--msgbox "Please Wait. This may take some time.\nYou can close this window. You'll be informed once the command completes." &
}

Init () {
	echo "Initializing device."

	if kdialog --style breeze --yesno "This will erase your device. Are you sure you wish to proceed?."; then
		DEVICE=$(GetDevice)

		showProgressDialog

		znx init $DEVICE &&
			showSuccess "Device initialized." ||
			showUnexpectedError
	fi
}

Deploy () {
	echo "Deploying image."

	DEVICE=$(GetDevice)
	IMAGENAME=$(GetName)
	IMAGEPATH=$(GetPath)

	showProgressDialog	

	znx deploy $DEVICE $IMAGENAME $IMAGEPATH &&
		showSuccess "Successfully deployed $IMAGENAME." ||
		showUnexpectedError
}

List () {	
	echo "Listing deployed images."

	DEVICE=$(GetDevice)

	showProgressDialog

	kdialog --style breeze --textbox $(znx list $DEVICE) ||
		showUnexpectedError
}

Update () {
	echo "Updating deployed image."

	DEVICE=$(GetDevice)
	IMAGENAME=$(GetName)

	showProgressDialog

	znx update $DEVICE $IMAGENAME &&
		showSuccess "Successfully updated $IMAGENAME." ||
		showUnexpectedError
}

Remove () {	
	echo "Removing deployed image."

	DEVICE=$(GetDevice)
	IMAGENAME=$(GetName)

	showProgressDialog

	znx remove $DEVICE $IMAGENAME &&
		showSuccess "Successfully removed $IMAGENAME" ||
		showUnexpectedError
}

while :; do
	OPTIONS="0 init on \
	1 deploy off \
	2 list off \
	3 update off \
	4 remove off"

	INPUT_OPTION=$(kdialog \
					--style breeze \
					--title "$TITLE" \
					--radiolist "Select the Function to run" $OPTIONS)

	case "$INPUT_OPTION" in
		0)
			Init
		;;

		1)
			Deploy
		;;

		2)
			List
		;;

		3)
			Update
		;;

		4)
			Remove
		;;

		*)
			break
		;;
	esac
done
