#!/bin/sh

PREREQ=""
DESCRIPTION="Setting up automatic login..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
prereqs)
       prereqs
       exit 0
       ;;
esac

# shellcheck source=/dev/null
. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# if [ -f /root/usr/bin/sddm ]; then
#     sddm_session=plasma.desktop
#     cat >>/root/etc/sddm.conf <<EOF
# [Autologin]
# User=$USERNAME
# Session=$sddm_session
# EOF
# fi

GREETD_CONFIG="/root/etc/greetd/config.toml"

if ! grep -q '^\[initial_session\]' "$GREETD_CONFIG"; then
    cat >> "$GREETD_CONFIG" <<EOF

# Enabling autologin

[initial_session]
command = "/usr/bin/env NWSM_REQUIRED_VARS=HYPRLAND_INSTANCE_SIGNATURE /usr/bin/nwsm -- /usr/bin/start-hyprland > /dev/null 2>&1"
user = "$USERNAME"
EOF
fi

log_end_msg
