#! /bin/sh

# - - - Prepare the directory for the modules.

mkdir -p build/initramfs/lib/modules/$kernel_version


# - - - Compile the kernel and its modules.

file=${kernel_url##*/}
source_dir=${file//.tar*}

if [[ ! -f build/sources/$source_dir/arch/x86/boot/bzImage ]]; then
	get-file $kernel_url

	if [ -f build/configs/kernel.config ]; then
		cp build/configs/kernel.config build/sources/$source_dir/.config
	else
		make -j $jobs -C build/sources/$source_dir defconfig
	fi

	make -j $jobs menuconfig \
		-C build/sources/$source_dir \
		INSTALL_MOD_PATH=$WD/build/initramfs \
		modules          \
		modules_install  \
		bzImage

	cp build/configs/kernel.config build/sources/$source_dir/.config
fi

mkdir -p build/iso/boot

cp build/sources/$source_dir/arch/x86/boot/bzImage build/iso/boot/linux
