#! /bin/sh

# - - - Install syslinux.

file=${syslinux_url##*/}
source_dir=${file//.tar*}

if [[ ! -d build/sources/$source_dir ]];then
	get-file $syslinux_url
fi

mkdir -p \
	build/iso/boot/isolinux \
	build/iso/boot/efi

cp build/sources/$source_dir/bios/core/isolinux.bin \
	build/sources/$source_dir/bios/com32/elflink/ldlinux/ldlinux.c32 \
	build/iso/boot/isolinux/

cmdline="default /boot/linux initrd=/boot/initramfs.gz splash root=$ROOTLABEL"
echo $cmdline > build/iso/boot/isolinux/isolinux.cfg

cmdline="\boot\linux initrd=\boot\initramfs.gz splash root=$ROOTLABEL"
echo $cmdline > build/iso/boot/efi/startup.nsh


# - - - Create the ISO file.

xorriso -as mkisofs build/iso/    \
	-o build/$iso_name.iso        \
	-iso-level 3                  \
	-no-emul-boot                 \
	-boot-load-size 4             \
	-boot-info-table              \
	-volid $ROOTLABEL             \
	-full-iso9660-filenames       \
	-c boot/isolinux/boot.cat     \
	-b boot/isolinux/isolinux.bin

isohybrid build/$iso_name.iso

say "Build finished. Saved as build/iso/$FILE.iso"
